################################################################################
#
# check-resolution command line utility
#
################################################################################

RECALBOX_CHECK_RESOLUTION_VERSION = 1.0
RECALBOX_CHECK_RESOLUTION_SITE = $(TOPDIR)/../projects/check-resolutions
RECALBOX_CHECK_RESOLUTION_SITE_METHOD = local
RECALBOX_CHECK_RESOLUTION_LICENSE = MIT
RECALBOX_CHECK_RESOLUTION_DEPENDENCIES = sdl2

ifeq ($(BR2_ENABLE_DEBUG),y)
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"
RECALBOX_CHECK_RESOLUTION_CONF_OPTS += -DUSE_KMSDRM=ON

$(eval $(cmake-package))
