#!/bin/bash

[[ "$1" != "start" ]] && exit 0

KEYPAD=/sys/devices/platform/odroidgo2-joypad

# disable then enable joypad
echo 0 > $KEYPAD/enable
echo 1 > $KEYPAD/enable

# calibrate current position of joypad
echo 1 > $KEYPAD/adc_cal
