#!/bin/bash
# this script is called by udev
# those envvar are passed from udev:
# ID_USB_CLASS_FROM_DATABASE=Miscellaneous Device
# ID_MODEL=802.11ac_NIC
# ID_REVISION=0200
# IFINDEX=5
# ID_SERIAL=Realtek_802.11ac_NIC_123456
# ID_BUS=usb
# PWD=/
# SEQNUM=5101
# ID_MODEL_ID=c820
# ID_VENDOR_ENC=Realtek
# DEVPATH=/devices/platform/soc/soc:usb3-0/12000000.dwc3/xhci-hcd.8.auto/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.2/net/wlan0
# USEC_INITIALIZED=804405941010
# ID_VENDOR_ID=0bda
# INTERFACE=wlan0
# SUBSYSTEM=net
# ID_USB_INTERFACES=:e00101:ffffff:
# ID_VENDOR_FROM_DATABASE=Realtek Semiconductor Corp.
# ID_SERIAL_SHORT=123456
# ID_MODEL_ENC=802.11ac\x20NIC
# ID_USB_PROTOCOL_FROM_DATABASE=Interface Association
# SHLVL=1
# ID_USB_INTERFACE_NUM=02
# DEVTYPE=wlan
# ID_USB_DRIVER=rtl8821cu
# ID_VENDOR=Realtek
# ID_TYPE=generic
# ID_NET_NAME_MAC=wlx54ef33487c31
# ACTION=add

source /recalbox/scripts/recalbox-wifi.sh

recallog -s "$(basename "$0")" -t "WIFI" "Configuring wifi for interface ${INTERFACE}"
cleanup_interface "$INTERFACE"
configure_interface "$INTERFACE"
