#!/usr/bin/expect -f
#Usage: recalpair XX:XX:XX:XX:XX:XX

set timeout 10
set prompt "#"
set address [lindex $argv 0]
set name [lindex $argv 1]

spawn bluetoothctl -a
expect -re $prompt

send "remove $address\r"
expect $prompt
expect {
  "Device has been removed" {
    send "quit\r"
    exit 1
  }
 "Device $address not available" {
  }
}

set timeout 60
send "scan on\r"
expect $prompt
expect {
  "*\] Device $address" {
  send "scan off\r"
  expect $prompt

  set timeout 10
  expect "Controller"

  # DS4 patch
  if { $name == "Wireless Controller" } {
    send "connect $address\r"
    expect "Connection successful"
    expect $prompt
  }

  send "pair $address\r"
  set timeout 5
  expect {
    "Enter PIN code:" {
      send "0000\r"
      expect $prompt
    }
  }
  set timeout 10
  expect "Pairing successful"
  expect $prompt

  send "trust $address\r"
  expect "Changing $address trust succeeded"
  expect $prompt

  send "connect $address\r"
  expect "Connection successful"
  expect $prompt

  send "quit\r"
  expect eof
  exit 0
  }
}
exit 1
