#!/usr/bin/expect -f
#Usage: recalpair XX:XX:XX:XX:XX:XX

set timeout 10
set prompt "#"
set address [lindex $argv 0]

spawn bluetoothctl -a
expect -re $prompt
send "remove $address\r"
sleep 1
expect {
  "Device has been removed" {
    send "quit\r"
    exit 1
  }
 "Device $address not available" {
  }
}
set timeout 60
send "scan on\r"
sleep 1
expect "*\] Device $address"
send "scan off\r"
set timeout 10
expect "Controller"
send "trust $address\r"
sleep 1
expect "Changing $address trust succeeded"
send "pair $address\r"
set timeout 5
expect "Enter PIN code:"
send "0000\r"
set timeout 10
expect "Pairing successful"
send "connect $address\r"
sleep 1
expect "Connection successful"
#send_user "\nShould be paired now.\r"
send "quit\r"
expect eof
