// this file was auto-generated by res2h

#pragma once

#include <string>
#include <map>

extern const uint16_t option_arrow_svg_size;
extern const uint8_t option_arrow_svg_data[];

extern const uint16_t arrow_svg_size;
extern const uint8_t arrow_svg_data[];

extern const uint16_t mire_recalbox_svg_size;
extern const uint8_t mire_recalbox_svg_data[];

extern const uint16_t off_svg_size;
extern const uint8_t off_svg_data[];

extern const uint16_t star_filled_svg_size;
extern const uint8_t star_filled_svg_data[];

extern const uint16_t textinput_ninepatch_png_size;
extern const uint8_t textinput_ninepatch_png_data[];

extern const uint16_t fav_add_svg_size;
extern const uint8_t fav_add_svg_data[];

extern const uint16_t plaincircle30_png_size;
extern const uint8_t plaincircle30_png_data[];

extern const uint32_t scroll_gradient_png_size;
extern const uint8_t scroll_gradient_png_data[];

extern const uint16_t busy_2_png_size;
extern const uint8_t busy_2_png_data[];

extern const uint32_t vk_ttf_size;
extern const uint8_t vk_ttf_data[];

extern const uint16_t busy_3_png_size;
extern const uint8_t busy_3_png_data[];

extern const uint16_t checkbox_checked_svg_size;
extern const uint8_t checkbox_checked_svg_data[];

extern const uint16_t thumbs_down_red_svg_size;
extern const uint8_t thumbs_down_red_svg_data[];

extern const uint16_t white_png_size;
extern const uint8_t white_png_data[];

extern const uint16_t star_unfilled_svg_size;
extern const uint8_t star_unfilled_svg_data[];

extern const uint16_t button_filled_png_size;
extern const uint8_t button_filled_png_data[];

extern const uint16_t button_png_size;
extern const uint8_t button_png_data[];

extern const uint16_t Recalbox_logo_White_svg_size;
extern const uint8_t Recalbox_logo_White_svg_data[];

extern const uint16_t thumbs_up_yellow_svg_size;
extern const uint8_t thumbs_up_yellow_svg_data[];

extern const uint16_t press_start_svg_size;
extern const uint8_t press_start_svg_data[];

extern const uint16_t splash_svg_size;
extern const uint8_t splash_svg_data[];

extern const uint16_t busy_0_png_size;
extern const uint8_t busy_0_png_data[];

extern const uint16_t heart_filled_svg_size;
extern const uint8_t heart_filled_svg_data[];

extern const uint16_t frame_png_size;
extern const uint8_t frame_png_data[];

extern const uint16_t recalbox_svg_size;
extern const uint8_t recalbox_svg_data[];

extern const uint16_t window_icon_256_png_size;
extern const uint8_t window_icon_256_png_data[];

extern const uint16_t no_image_png_size;
extern const uint8_t no_image_png_data[];

extern const uint16_t fav_remove_svg_size;
extern const uint8_t fav_remove_svg_data[];

extern const uint16_t Recalbox_logo_Grey_svg_size;
extern const uint8_t Recalbox_logo_Grey_svg_data[];

extern const uint16_t thumbs_up_green_svg_size;
extern const uint8_t thumbs_up_green_svg_data[];

extern const uint16_t slider_knob_svg_size;
extern const uint8_t slider_knob_svg_data[];

extern const uint16_t busy_1_png_size;
extern const uint8_t busy_1_png_data[];

extern const uint32_t ubuntu_condensed_ttf_size;
extern const uint8_t ubuntu_condensed_ttf_data[];

extern const uint16_t on_svg_size;
extern const uint8_t on_svg_data[];

extern const uint16_t textinput_ninepatch_active_png_size;
extern const uint8_t textinput_ninepatch_active_png_data[];

extern const uint16_t question_svg_size;
extern const uint8_t question_svg_data[];

extern const uint16_t checkbox_unchecked_svg_size;
extern const uint8_t checkbox_unchecked_svg_data[];

extern const uint16_t genre__action_svg_size;
extern const uint8_t genre__action_svg_data[];

extern const uint16_t genre__rpgaction_svg_size;
extern const uint8_t genre__rpgaction_svg_data[];

extern const uint16_t genre__adventurerealtime3d_svg_size;
extern const uint8_t genre__adventurerealtime3d_svg_data[];

extern const uint16_t genre__flipper_svg_size;
extern const uint8_t genre__flipper_svg_data[];

extern const uint16_t genre__party_svg_size;
extern const uint8_t genre__party_svg_data[];

extern const uint16_t genre__actionshootemup_svg_size;
extern const uint8_t genre__actionshootemup_svg_data[];

extern const uint16_t genre__simulationbuildandmanagement_svg_size;
extern const uint8_t genre__simulationbuildandmanagement_svg_data[];

extern const uint16_t genre__adventuretext_svg_size;
extern const uint8_t genre__adventuretext_svg_data[];

extern const uint16_t genre__digitalcard_svg_size;
extern const uint8_t genre__digitalcard_svg_data[];

extern const uint16_t genre__casino_svg_size;
extern const uint8_t genre__casino_svg_data[];

extern const uint16_t genre__adventure_svg_size;
extern const uint8_t genre__adventure_svg_data[];

extern const uint16_t genre__sportsimulation_svg_size;
extern const uint8_t genre__sportsimulation_svg_data[];

extern const uint16_t genre__rpgdungeoncrawler_svg_size;
extern const uint8_t genre__rpgdungeoncrawler_svg_data[];

extern const uint16_t genre__puzzleandlogic_svg_size;
extern const uint8_t genre__puzzleandlogic_svg_data[];

extern const uint16_t genre__sportcompetitive_svg_size;
extern const uint8_t genre__sportcompetitive_svg_data[];

extern const uint16_t genre__actionfighting_svg_size;
extern const uint8_t genre__actionfighting_svg_data[];

extern const uint16_t genre__simulationscifi_svg_size;
extern const uint8_t genre__simulationscifi_svg_data[];

extern const uint16_t genre__simulationvehicle_svg_size;
extern const uint8_t genre__simulationvehicle_svg_data[];

extern const uint16_t genre__strategywargame_svg_size;
extern const uint8_t genre__strategywargame_svg_data[];

extern const uint16_t genre__adventuregraphical_svg_size;
extern const uint8_t genre__adventuregraphical_svg_data[];

extern const uint16_t genre__simulationlife_svg_size;
extern const uint8_t genre__simulationlife_svg_data[];

extern const uint16_t genre__strategyautobattler_svg_size;
extern const uint8_t genre__strategyautobattler_svg_data[];

extern const uint16_t genre__actionplatformshooter_svg_size;
extern const uint8_t genre__actionplatformshooter_svg_data[];

extern const uint16_t genre__demoscene_svg_size;
extern const uint8_t genre__demoscene_svg_data[];

extern const uint16_t genre__rpgtactical_svg_size;
extern const uint8_t genre__rpgtactical_svg_data[];

extern const uint16_t genre__actionbeatemup_svg_size;
extern const uint8_t genre__actionbeatemup_svg_data[];

extern const uint16_t genre__rpgmmo_svg_size;
extern const uint8_t genre__rpgmmo_svg_data[];

extern const uint16_t genre__casual_svg_size;
extern const uint8_t genre__casual_svg_data[];

extern const uint16_t genre__strategyrts_svg_size;
extern const uint8_t genre__strategyrts_svg_data[];

extern const uint16_t genre__sportfight_svg_size;
extern const uint8_t genre__sportfight_svg_data[];

extern const uint16_t genre__strategy4x_svg_size;
extern const uint8_t genre__strategy4x_svg_data[];

extern const uint16_t genre__adventureinteractivemovie_svg_size;
extern const uint8_t genre__adventureinteractivemovie_svg_data[];

extern const uint16_t genre__adventuresurvivalhorror_svg_size;
extern const uint8_t genre__adventuresurvivalhorror_svg_data[];

extern const uint16_t genre__board_svg_size;
extern const uint8_t genre__board_svg_data[];

extern const uint16_t genre__strategytowerdefense_svg_size;
extern const uint8_t genre__strategytowerdefense_svg_data[];

extern const uint16_t genre__rpgfirstpersonpartybased_svg_size;
extern const uint8_t genre__rpgfirstpersonpartybased_svg_data[];

extern const uint16_t genre__actionrythm_svg_size;
extern const uint8_t genre__actionrythm_svg_data[];

extern const uint16_t genre__trivia_svg_size;
extern const uint8_t genre__trivia_svg_data[];

extern const uint16_t genre__compilation_svg_size;
extern const uint8_t genre__compilation_svg_data[];

extern const uint16_t genre__rpg_svg_size;
extern const uint8_t genre__rpg_svg_data[];

extern const uint16_t genre__strategyartillery_svg_size;
extern const uint8_t genre__strategyartillery_svg_data[];

extern const uint16_t genre__educative_svg_size;
extern const uint8_t genre__educative_svg_data[];

extern const uint16_t genre__strategytbs_svg_size;
extern const uint8_t genre__strategytbs_svg_data[];

extern const uint16_t genre__adventurevisualnovel_svg_size;
extern const uint8_t genre__adventurevisualnovel_svg_data[];

extern const uint16_t genre__strategymoba_svg_size;
extern const uint8_t genre__strategymoba_svg_data[];

extern const uint16_t genre__simulation_svg_size;
extern const uint8_t genre__simulation_svg_data[];

extern const uint16_t genre__actionfirstpersonshooter_svg_size;
extern const uint8_t genre__actionfirstpersonshooter_svg_data[];

extern const uint16_t genre__sportracing_svg_size;
extern const uint8_t genre__sportracing_svg_data[];

extern const uint16_t genre__actionplatformer_svg_size;
extern const uint8_t genre__actionplatformer_svg_data[];

extern const uint16_t genre__actionstealth_svg_size;
extern const uint8_t genre__actionstealth_svg_data[];

extern const uint16_t genre__strategy_svg_size;
extern const uint8_t genre__strategy_svg_data[];

extern const uint16_t genre__sports_svg_size;
extern const uint8_t genre__sports_svg_data[];

extern const uint16_t genre__rpgjapanese_svg_size;
extern const uint8_t genre__rpgjapanese_svg_data[];

extern const uint16_t genre__actionshootwithgun_svg_size;
extern const uint8_t genre__actionshootwithgun_svg_data[];

extern const uint16_t genre__simulationfishandhunt_svg_size;
extern const uint8_t genre__simulationfishandhunt_svg_data[];

extern const uint16_t genre__actionbattleroyale_svg_size;
extern const uint8_t genre__actionbattleroyale_svg_data[];

extern const uint16_t help__dpad_down_svg_size;
extern const uint8_t help__dpad_down_svg_data[];

extern const uint16_t help__joystick_down_R_svg_size;
extern const uint8_t help__joystick_down_R_svg_data[];

extern const uint16_t help__button_x_svg_size;
extern const uint8_t help__button_x_svg_data[];

extern const uint16_t help__brightness_down_svg_size;
extern const uint8_t help__brightness_down_svg_data[];

extern const uint16_t help__button_hotkey_svg_size;
extern const uint8_t help__button_hotkey_svg_data[];

extern const uint16_t help__button_y_svg_size;
extern const uint8_t help__button_y_svg_data[];

extern const uint16_t help__joystick_left_svg_size;
extern const uint8_t help__joystick_left_svg_data[];

extern const uint16_t help__volume_down_svg_size;
extern const uint8_t help__volume_down_svg_data[];

extern const uint16_t help__button_l_svg_size;
extern const uint8_t help__button_l_svg_data[];

extern const uint16_t help__joystick_updown_L_svg_size;
extern const uint8_t help__joystick_updown_L_svg_data[];

extern const uint16_t help__button_l3_svg_size;
extern const uint8_t help__button_l3_svg_data[];

extern const uint16_t help__joystick_all_R_svg_size;
extern const uint8_t help__joystick_all_R_svg_data[];

extern const uint16_t help__dpad_updown_svg_size;
extern const uint8_t help__dpad_updown_svg_data[];

extern const uint16_t help__joystick_left_R_svg_size;
extern const uint8_t help__joystick_left_R_svg_data[];

extern const uint16_t help__dpad_all_svg_size;
extern const uint8_t help__dpad_all_svg_data[];

extern const uint16_t help__dpad_left_svg_size;
extern const uint8_t help__dpad_left_svg_data[];

extern const uint16_t help__brightness_up_svg_size;
extern const uint8_t help__brightness_up_svg_data[];

extern const uint16_t help__joystick_leftright_R_svg_size;
extern const uint8_t help__joystick_leftright_R_svg_data[];

extern const uint16_t help__button_b_svg_size;
extern const uint8_t help__button_b_svg_data[];

extern const uint16_t help__button_lr_svg_size;
extern const uint8_t help__button_lr_svg_data[];

extern const uint16_t help__joystick_right_R_svg_size;
extern const uint8_t help__joystick_right_R_svg_data[];

extern const uint16_t help__joystick_right_L_svg_size;
extern const uint8_t help__joystick_right_L_svg_data[];

extern const uint16_t help__dpad_right_svg_size;
extern const uint8_t help__dpad_right_svg_data[];

extern const uint16_t help__button_r_svg_size;
extern const uint8_t help__button_r_svg_data[];

extern const uint16_t help__dpad_leftright_svg_size;
extern const uint8_t help__dpad_leftright_svg_data[];

extern const uint16_t help__button_l2_svg_size;
extern const uint8_t help__button_l2_svg_data[];

extern const uint16_t help__joystick_up_L_svg_size;
extern const uint8_t help__joystick_up_L_svg_data[];

extern const uint16_t help__button_r2_svg_size;
extern const uint8_t help__button_r2_svg_data[];

extern const uint16_t help__dpad_up_svg_size;
extern const uint8_t help__dpad_up_svg_data[];

extern const uint16_t help__joystick_left_L_svg_size;
extern const uint8_t help__joystick_left_L_svg_data[];

extern const uint16_t help__button_select_svg_size;
extern const uint8_t help__button_select_svg_data[];

extern const uint16_t help__button_a_svg_size;
extern const uint8_t help__button_a_svg_data[];

extern const uint16_t help__volume_up_svg_size;
extern const uint8_t help__volume_up_svg_data[];

extern const uint16_t help__joystick_up_R_svg_size;
extern const uint8_t help__joystick_up_R_svg_data[];

extern const uint16_t help__button_start_svg_size;
extern const uint8_t help__button_start_svg_data[];

extern const uint16_t help__button_l2r2_svg_size;
extern const uint8_t help__button_l2r2_svg_data[];

extern const uint16_t help__joystick_all_L_svg_size;
extern const uint8_t help__joystick_all_L_svg_data[];

extern const uint16_t help__button_r3_svg_size;
extern const uint8_t help__button_r3_svg_data[];

extern const uint16_t help__joystick_leftright_L_svg_size;
extern const uint8_t help__joystick_leftright_L_svg_data[];

extern const uint16_t help__joystick_up_svg_size;
extern const uint8_t help__joystick_up_svg_data[];

extern const uint16_t help__joystick_updown_R_svg_size;
extern const uint8_t help__joystick_updown_R_svg_data[];

extern const uint16_t help__joystick_down_L_svg_size;
extern const uint8_t help__joystick_down_L_svg_data[];

extern const uint16_t crt__pattern480_png_size;
extern const uint8_t crt__pattern480_png_data[];

extern const uint16_t crt__pattern240_png_size;
extern const uint8_t crt__pattern240_png_data[];

extern const uint32_t crt__logo_png_size;
extern const uint8_t crt__logo_png_data[];

struct Res2hEntry {
    const std::string relativeFileName;
    const uint32_t size;
    const uint8_t * data;
};

extern const uint32_t res2hNrOfFiles;
extern const Res2hEntry res2hFiles[];

typedef const std::map<const std::string, const Res2hEntry> res2hMapType;
extern res2hMapType res2hMap;
