#!/bin/bash

if test "$1" == "start" ; then
    CONFIG_LINE=$(grep -m 1 -e "^system.crt=.*" /recalbox/share/system/recalbox.conf)
    DAC=${CONFIG_LINE##*=}
    CRT_CONFIG_FILE="/boot/recalbox-crt-config.txt"
    CRT_TIMING_FILE="/boot/timings.txt"

    if [[ "${DAC}" == "vga666" || "${DAC}" == "rgbpi" || "${DAC}" == "pi2scart" ]];then
        if [[ ! -f "${CRT_CONFIG_FILE}" ]] || ! grep -q "#device=${DAC}" /boot/recalbox-crt-config.txt; then
            source /recalbox/scripts/recalbox-utils.sh
            recallog -s "S13crt" -t "CRT" "Processing ${DAC} configuration."
            mount -o remount,rw /boot
            recallog -s "S13crt" -t "CRT" "Installing timings and config in /boot"
            cp "/boot/crt-config/${DAC}-config.txt" "${CRT_CONFIG_FILE}"
            cp "/boot/crt-config/timings.txt" "${CRT_TIMING_FILE}"
            mount -o remount,ro /boot
            recallog -s "S13crt" -t "CRT" "Adding configuration in recalbox.conf"
            killall -9 emulationstation
            sed -i "s/^emulationstation\.theme\.recalbox-next\.systemview=.*/emulationstation.theme.recalbox-next.systemview=3-crt and tiny screen/g" \
              /recalbox/share/system/recalbox.conf
            sed -i "s/^emulationstation\.theme\.recalbox-next\.gamelistview=.*/emulationstation.theme.recalbox-next.gamelistview=6-crt-small screen/g" \
              /recalbox/share/system/recalbox.conf
            reboot
        fi
    elif [[ "${DAC}" == "" ]]; then
        if [[ -f "${CRT_CONFIG_FILE}" ]]; then
            # We should clean
            source /recalbox/scripts/recalbox-utils.sh
            recallog -s "S13crt" -t "CRT" "Uninstalling CRT configuration."
            mount -o remount,rw /boot
            mkdir -p /boot/crt-config-save/
            recallog -s "S13crt" -t "CRT" "Moving timings and config in /boot/crt-config-save"
            mv "${CRT_CONFIG_FILE}" "${CRT_TIMING_FILE}" /boot/crt-config-save/
            touch "${CRT_CONFIG_FILE}"
            recallog -s "S13crt" -t "CRT" "Removing retroarch-custom.cfg and retroarch-core-options.cfg"
            rm -rf "/recalbox/share/system/configs/retroarch/retroarchcustom.cfg" "/recalbox/share/system/configs/retroarch/cores/retroarch-core-options.cfg"
            recallog -s "S13crt" -t "CRT" "Removing configuration in recalbox.conf"
            killall -9 emulationstation
            sed -i "/emulationstation.theme.recalbox-next.systemview=3-crt and tiny screen/d" /recalbox/share/system/recalbox.conf
            sed -i "/emulationstation.theme.recalbox-next.gamelistview=6-crt-small screen/d" /recalbox/share/system/recalbox.conf
            mount -o remount,ro /boot
            reboot
        fi
    else
        # Unsupported
        source /recalbox/scripts/recalbox-utils.sh
        recallog -s "S13crt" -t "CRT" "Unable to process ${DAC} configuration. Not supported yet."
    fi
fi