################################################################################
#
# busybox_initramfs
#
################################################################################

#RECALBOX_INITRAMFS_VERSION = 1.25.1
RECALBOX_INITRAMFS_VERSION = $(BUSYBOX_VERSION)
RECALBOX_INITRAMFS_SITE = http://www.busybox.net/downloads
RECALBOX_INITRAMFS_SOURCE = busybox-$(RECALBOX_INITRAMFS_VERSION).tar.bz2
RECALBOX_INITRAMFS_LICENSE = GPLv2
RECALBOX_INITRAMFS_LICENSE_FILES = LICENSE

RECALBOX_INITRAMFS_CFLAGS = $(TARGET_CFLAGS)
RECALBOX_INITRAMFS_LDFLAGS = $(TARGET_LDFLAGS)

RECALBOX_INITRAMFS_KCONFIG_FILE = "$(RECALBOX_INITRAMFS_PKGDIR)/busybox.config"

RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR=$(BINARIES_DIR)/initramfs

# Allows the build system to tweak CFLAGS
RECALBOX_INITRAMFS_MAKE_ENV = \
	$(TARGET_MAKE_ENV) \
	CFLAGS="$(RECALBOX_INITRAMFS_CFLAGS)"
RECALBOX_INITRAMFS_MAKE_OPTS = \
	CC="$(TARGET_CC)" \
	ARCH=$(KERNEL_ARCH) \
	PREFIX="$(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR)" \
	EXTRA_LDFLAGS="$(RECALBOX_INITRAMFS_LDFLAGS)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	CONFIG_PREFIX="$(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR)" \
	SKIP_STRIP=y

RECALBOX_INITRAMFS_KCONFIG_OPTS = $(RECALBOX_INITRAMFS_MAKE_OPTS)

define RECALBOX_INITRAMFS_BUILD_CMDS
	$(RECALBOX_INITRAMFS_MAKE_ENV) $(MAKE) $(RECALBOX_INITRAMFS_MAKE_OPTS) -C $(@D)
endef

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2)$(BR2_PACKAGE_RECALBOX_TARGET_ODROIDXU4),y)

RECALBOX_INITRAMFS_DEPENDENCIES += host-uboot-tools

ifeq ($(BR2_aarch64)$(BR2_TOOLCHAIN_OPTIONAL_LINARO_AARCH64),y)
RECALBOX_INITRAMFS_INITRDA=arm64
else
RECALBOX_INITRAMFS_INITRDA=arm
endif

define RECALBOX_INITRAMFS_INSTALL_TARGET_CMDS
	mkdir -p $(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR)/{new_root,sys,proc}
	cp $(RECALBOX_INITRAMFS_PKGDIR)/init $(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR)/init
	$(RECALBOX_INITRAMFS_MAKE_ENV) $(MAKE) $(RECALBOX_INITRAMFS_MAKE_OPTS) -C $(@D) install
	(cd $(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR) && find . | cpio -H newc -o > $(BINARIES_DIR)/initrd)
	(cd $(BINARIES_DIR) && $(HOST_DIR)/bin/mkimage -A $(RECALBOX_INITRAMFS_INITRDA) -O linux -T ramdisk -C none -a 0 -e 0 -n initrd -d ./initrd ./uInitrd)
endef

else

define RECALBOX_INITRAMFS_INSTALL_TARGET_CMDS
	mkdir -p $(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR)/{new_root,sys,proc}
	cp $(RECALBOX_INITRAMFS_PKGDIR)/init $(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR)/init
	$(RECALBOX_INITRAMFS_MAKE_ENV) $(MAKE) $(RECALBOX_INITRAMFS_MAKE_OPTS) -C $(@D) install
	(cd $(RECALBOX_INITRAMFS_BINARIES_INITRAMFSDIR) && find . | cpio -H newc -o | gzip -9 > $(BINARIES_DIR)/initrd.gz)
endef

endif

$(eval $(kconfig-package))
