################################################################################
#
# drm adapter
#
################################################################################

DRMADAPTER_VERSION = e1a39f213988254dbe63214b6556387f6e79cc60
DRMADAPTER_SITE = https://gitlab.com/recalbox/recalbox-drm-video-adapter.git
DRMADAPTER_SITE_METHOD = git
DRMADAPTER_LICENSE = MIT

DRMADAPTER_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
DRMADAPTER_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
DRMADAPTER_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
DRMADAPTER_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
DRMADAPTER_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
DRMADAPTER_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
DRMADAPTER_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
DRMADAPTER_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"

define DRMADAPTER_INSTALL_STARTUP_SCRIPT
	$(INSTALL) -m 0755 -D $(DRMADAPTER_PKGDIR)/S02drmadapter $(TARGET_DIR)/etc/init.d/S02drmadapter
endef

DRMADAPTER_POST_INSTALL_TARGET_HOOKS += DRMADAPTER_INSTALL_STARTUP_SCRIPT

$(eval $(cmake-package))
