#!/usr/bin/expect -f
#Usage: recalpair XX:XX:XX:XX:XX:XX "name"

set timeout 10
set prompt "#"
set address [lindex $argv 0]
set name [lindex $argv 1]

eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Pairing bluetooth device $name with mac $address...\""

spawn bluetoothctl
expect -re $prompt

send "remove $address\r"
expect $prompt
expect {
  "Device has been removed" {
    send "quit\r"
    eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Pairing failed because device was already paired. Please try again.\""
    exit 1
  }
 "Device $address not available" {
  }
}

set timeout 60
eval exec "echo state=0" > /tmp/bt_state
eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Scanning...\""
send "scan on\r"
expect $prompt
expect {
  "*\] Device $address" {
  send "scan off\r"
  expect $prompt
  eval exec "echo state=1" > /tmp/bt_state
  eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Device found. Pairing...\""

  set timeout 10
  expect "Controller"

  eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Pairing...\""
  send "pair $address\r"
  expect {
    "Enter PIN code:" {
      eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Pin code asked...\""
      send "0000\r"
      expect $prompt
      eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Pin code entered!\""
      exp_continue
    }
    "Pairing successful" {
      expect $prompt
      eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Paired!\""
      eval exec "echo state=2" > /tmp/bt_state
    }
    "Failed to pair: org.bluez.Error.AlreadyExists" {
      expect $prompt
      eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Paired!\""
      eval exec "echo state=2" > /tmp/bt_state
    }
  }

  eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Trusting...\""
  send "trust $address\r"
  expect "Changing $address trust succeeded"
  expect $prompt
  eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Trusted!\""
  eval exec "echo state=3" > /tmp/bt_state

  eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Connecting...\""
  send "connect $address\r"
  expect "Connection successful"
  expect $prompt
  eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Connected!\""
  eval exec "echo state=4" > /tmp/bt_state

  eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Device $name pairing ended.\""
  send "quit\r"
  expect eof
  exit 0
  }
}
eval exec "recallog -s \"recalpair\" -t \"BLUETOOTH\" \"Pairing failed because device was not found.\""
exit 1
