while read -r directory
do
    mkdir -p "$directory"
done < <(echo "./obj/m
./obj/m/linux
./obj/m/linux/blend
./obj/m/linux/blend/m
./obj/m/linux/blend/lib
./obj/m/linux/blend/linux
./obj/menu
./obj/menu/linux
./obj/menu/linux/blend
./obj/menu/linux/blend/menu
./obj/menu/linux/blend/lib
./obj/menu/linux/blend/linux
./obj/menu/linux/blend/blit
./obj/menu/linux/blend/sdl
./obj/menu/linux/blend/mpglib
./obj/j
./obj/j/linux
./obj/j/linux/blend
./obj/j/linux/blend/lib
./obj/j/linux/blend/j
./obj/j/linux/blend/linux
./obj/j/linux/blend/sdl
./obj/mame
./obj/mame/linux
./obj/mame/linux/blend
./obj/mame/linux/blend/sndhrdw
./obj/mame/linux/blend/debug
./obj/mame/linux/blend/advance
./obj/mame/linux/blend/advance/lib
./obj/mame/linux/blend/advance/linux
./obj/mame/linux/blend/advance/osd
./obj/mame/linux/blend/advance/blit
./obj/mame/linux/blend/advance/sdl
./obj/mame/linux/blend/machine
./obj/mame/linux/blend/cpu
./obj/mame/linux/blend/cpu/nec
./obj/mame/linux/blend/cpu/adsp2100
./obj/mame/linux/blend/cpu/i8x41
./obj/mame/linux/blend/cpu/i8039
./obj/mame/linux/blend/cpu/m6800
./obj/mame/linux/blend/cpu/i960
./obj/mame/linux/blend/cpu/jaguar
./obj/mame/linux/blend/cpu/dsp32
./obj/mame/linux/blend/cpu/i8085
./obj/mame/linux/blend/cpu/m6809
./obj/mame/linux/blend/cpu/arm7
./obj/mame/linux/blend/cpu/konami
./obj/mame/linux/blend/cpu/tms32031
./obj/mame/linux/blend/cpu/rsp
./obj/mame/linux/blend/cpu/z8000
./obj/mame/linux/blend/cpu/t11
./obj/mame/linux/blend/cpu/powerpc
./obj/mame/linux/blend/cpu/spc700
./obj/mame/linux/blend/cpu/r3000
./obj/mame/linux/blend/cpu/sh2
./obj/mame/linux/blend/cpu/ccpu
./obj/mame/linux/blend/cpu/upd7810
./obj/mame/linux/blend/cpu/v810
./obj/mame/linux/blend/cpu/i8051
./obj/mame/linux/blend/cpu/m6805
./obj/mame/linux/blend/cpu/arm
./obj/mame/linux/blend/cpu/mips
./obj/mame/linux/blend/cpu/asap
./obj/mame/linux/blend/cpu/alph8201
./obj/mame/linux/blend/cpu/m37710
./obj/mame/linux/blend/cpu/pic16c5x
./obj/mame/linux/blend/cpu/tms32051
./obj/mame/linux/blend/cpu/sharc
./obj/mame/linux/blend/cpu/m6502
./obj/mame/linux/blend/cpu/i386
./obj/mame/linux/blend/cpu/i86
./obj/mame/linux/blend/cpu/tms34010
./obj/mame/linux/blend/cpu/z80
./obj/mame/linux/blend/cpu/dsp56k
./obj/mame/linux/blend/cpu/z180
./obj/mame/linux/blend/cpu/se3208
./obj/mame/linux/blend/cpu/g65816
./obj/mame/linux/blend/cpu/tms32010
./obj/mame/linux/blend/cpu/h6280
./obj/mame/linux/blend/cpu/tms9900
./obj/mame/linux/blend/cpu/m68000
./obj/mame/linux/blend/cpu/tms32025
./obj/mame/linux/blend/cpu/h83002
./obj/mame/linux/blend/cpu/mc68hc11
./obj/mame/linux/blend/cpu/e132xs
./obj/mame/linux/blend/cpu/hd6309
./obj/mame/linux/blend/cpu/s2650
./obj/mame/linux/blend/cpu/v60
./obj/mame/linux/blend/vidhrdw
./obj/mame/linux/blend/sound
./obj/mame/linux/blend/drivers
./obj/d2
./obj/d2/linux
./obj/d2/linux/d2
./obj/blue
./obj/blue/linux
./obj/blue/linux/blend
./obj/blue/linux/blend/lib
./obj/blue/linux/blend/blue
./obj/s
./obj/s/linux
./obj/s/linux/blend
./obj/s/linux/blend/lib
./obj/s/linux/blend/linux
./obj/s/linux/blend/s
./obj/s/linux/blend/sdl
./obj/s/linux/blend/mpglib
./obj/cfg
./obj/cfg/linux
./obj/cfg/linux/blend
./obj/cfg/linux/blend/lib
./obj/cfg/linux/blend/linux
./obj/cfg/linux/blend/blit
./obj/cfg/linux/blend/cfg
./obj/cfg/linux/blend/v
./obj/v
./obj/v/linux
./obj/v/linux/blend
./obj/v/linux/blend/lib
./obj/v/linux/blend/linux
./obj/v/linux/blend/blit
./obj/v/linux/blend/v
./obj/mess
./obj/mess/linux
./obj/mess/linux/blend
./obj/mess/linux/blend/sndhrdw
./obj/mess/linux/blend/debug
./obj/mess/linux/blend/advance
./obj/mess/linux/blend/advance/lib
./obj/mess/linux/blend/advance/linux
./obj/mess/linux/blend/advance/osd
./obj/mess/linux/blend/advance/blit
./obj/mess/linux/blend/advance/sdl
./obj/mess/linux/blend/machine
./obj/mess/linux/blend/cpu
./obj/mess/linux/blend/cpu/nec
./obj/mess/linux/blend/cpu/i8039
./obj/mess/linux/blend/cpu/m6800
./obj/mess/linux/blend/cpu/jaguar
./obj/mess/linux/blend/cpu/i8085
./obj/mess/linux/blend/cpu/m6809
./obj/mess/linux/blend/cpu/rsp
./obj/mess/linux/blend/cpu/powerpc
./obj/mess/linux/blend/cpu/spc700
./obj/mess/linux/blend/cpu/sh2
./obj/mess/linux/blend/cpu/m6805
./obj/mess/linux/blend/cpu/arm
./obj/mess/linux/blend/cpu/mips
./obj/mess/linux/blend/cpu/m6502
./obj/mess/linux/blend/cpu/i386
./obj/mess/linux/blend/cpu/i86
./obj/mess/linux/blend/cpu/z80
./obj/mess/linux/blend/cpu/z180
./obj/mess/linux/blend/cpu/g65816
./obj/mess/linux/blend/cpu/h6280
./obj/mess/linux/blend/cpu/tms9900
./obj/mess/linux/blend/cpu/m68000
./obj/mess/linux/blend/cpu/e132xs
./obj/mess/linux/blend/cpu/hd6309
./obj/mess/linux/blend/cpu/s2650
./obj/mess/linux/blend/vidhrdw
./obj/mess/linux/blend/mess
./obj/mess/linux/blend/mess/expat
./obj/mess/linux/blend/mess/sndhrdw
./obj/mess/linux/blend/mess/tools
./obj/mess/linux/blend/mess/tools/mkimage
./obj/mess/linux/blend/mess/tools/messroms
./obj/mess/linux/blend/mess/tools/mkhdimg
./obj/mess/linux/blend/mess/tools/dat2html
./obj/mess/linux/blend/mess/tools/imgtool
./obj/mess/linux/blend/mess/systems
./obj/mess/linux/blend/mess/formats
./obj/mess/linux/blend/mess/devices
./obj/mess/linux/blend/mess/machine
./obj/mess/linux/blend/mess/cpu
./obj/mess/linux/blend/mess/cpu/cdp1802
./obj/mess/linux/blend/mess/cpu/tms7000
./obj/mess/linux/blend/mess/cpu/apexc
./obj/mess/linux/blend/mess/cpu/cp1610
./obj/mess/linux/blend/mess/cpu/sc61860
./obj/mess/linux/blend/mess/cpu/z80gb
./obj/mess/linux/blend/mess/cpu/saturn
./obj/mess/linux/blend/mess/cpu/pdp1
./obj/mess/linux/blend/mess/cpu/f8
./obj/mess/linux/blend/mess/cpu/cop411
./obj/mess/linux/blend/mess/cpu/sm8500
./obj/mess/linux/blend/mess/cpu/v30mz
./obj/mess/linux/blend/mess/vidhrdw
./obj/mess/linux/blend/mess/sound
./obj/mess/linux/blend/sound
./obj/mess/linux/blend/drivers
./obj/k
./obj/k/linux
./obj/k/linux/blend
./obj/k/linux/blend/lib
./obj/k/linux/blend/linux
./obj/k/linux/blend/k")