#!/bin/sh

# Additional options
OPTIONS=""

NAME="wsdd2"
DAEMON="/usr/sbin/${NAME}"

# Sanity checks
test -f ${DAEMON} || exit 0

case "$1" in
	start)
		printf "Starting WSD server: "
		start-stop-daemon -S -q -x ${DAEMON} -- -d $OPTIONS
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping WSD server: "
		start-stop-daemon -K -q -x ${DAEMON}
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart | force-reload)
		$0 stop
		$0 start
		if [ "$?" != "0" ]; then
			exit 1
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload}"
		exit 1
esac

exit 0
