################################################################################
#
# MUPEN64PLUS-NX
#
################################################################################

LIBRETRO_MUPEN64PLUS_NX_VERSION = 350f90a73cf0f5d65357ce982ccbaa3b22fc3569
LIBRETRO_MUPEN64PLUS_NX_SITE = $(call github,libretro,mupen64plus-libretro-nx,$(LIBRETRO_MUPEN64PLUS_NX_VERSION))
LIBRETRO_MUPEN64PLUS_NX_LICENSE = GPLv3
LIBRETRO_MUPEN64PLUS_NX_DEPENDENCIES += host-nasm

ifeq ($(BR2_PACKAGE_HAS_LIBEGL),y)
LIBRETRO_MUPEN64PLUS_NX_DEPENDENCIES += libegl
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_MUPEN64PLUS_NX_DEPENDENCIES += libgl
endif

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2LEGACY),y)
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=rpi3

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI3)$(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2),y)
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=rpi3 mesa

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4_64),y)
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=rpi4_64 mesa

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDXU4),y)
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=odroid
LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT=BOARD="ODROID-XU"

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=odroid64
LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT=BOARD="ODROID-GO2" EGL_LIB="-lEGL -lmali"

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RG353X),y)
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=unix
LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT= EGL_LIB="-lEGL -lmali"

else ifeq ($(BR2_x86_64),y)
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=unix
LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT= HAVE_PARALLEL_RSP=1 HAVE_THR_AL=1 LLE=1

else
LIBRETRO_MUPEN64PLUS_NX_PLATFORM=$(RETROARCH_LIBRETRO_BOARD)
LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT=
endif

ifeq ($(BR2_PACKAGE_RECALBOX_HAS_LIBGLES),y)
LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT += FORCE_GLES=1
endif

ifeq ($(BR2_PACKAGE_RECALBOX_HAS_LIBGLES3),y)
LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT += FORCE_GLES3=1
endif

LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT += ARCH=$(BR2_ARCH)
LIBRETRO_MUPEN64PLUS_NX_DYNAREC = $(BR2_ARCH)

define LIBRETRO_MUPEN64PLUS_NX_BUILD_CMDS
	$(SED) "s|-O2|-O3|g" $(@D)/Makefile
	CFLAGS="$(TARGET_CFLAGS) $(COMPILER_COMMONS_CFLAGS_SO)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) $(COMPILER_COMMONS_CXXFLAGS_SO)" \
		CPPFLAGS="$(TARGET_CPPFLAGS) $(COMPILER_COMMONS_CPPFLAGS_SO)" \
		$(MAKE) NASM="$(HOST_DIR)/bin/nasm" CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" LD="$(TARGET_LD)" \
		AR="$(TARGET_AR)" RANLIB="$(TARGET_RANLIB)" -C $(@D)/ -f Makefile platform="$(LIBRETRO_MUPEN64PLUS_NX_PLATFORM)" $(LIBRETRO_MUPEN64PLUS_NX_SUPP_OPT) \
		WITH_DYNAREC=$(LIBRETRO_MUPEN64PLUS_NX_DYNAREC)
endef

define LIBRETRO_MUPEN64PLUS_NX_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/mupen64plus_next_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/mupen64plus_next_libretro.so
	mkdir -p $(TARGET_DIR)/recalbox/share_upgrade/bios/Mupen64plus/hires_texture
	mkdir -p $(TARGET_DIR)/recalbox/share_upgrade/bios/Mupen64plus/cache
endef

$(eval $(generic-package))
