################################################################################
#
# fbv - Recalbox version
#
################################################################################

FBV_RECALBOX_VERSION = 6157e3d4c8be5944688c4c2c2392a25c42f98f44
FBV_RECALBOX_SITE = https://gitlab.com/Bkg2k/fbv.git
FBV_RECALBOX_SITE_METHOD = git
FBV_RECALBOX_LICENSE = GPL-2.0
FBV_RECALBOX_LICENSE_FILES = COPYING
FBV_RECALBOX_DEPENDENCIES = libpng jpeg giflib

FBV_RECALBOX_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
FBV_RECALBOX_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
FBV_RECALBOX_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
FBV_RECALBOX_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"
FBV_RECALBOX_CONF_OPTS += -DOPTION_RECALBOX_PRODUCTION_BUILD=true

define FBV_RECALBOX_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/fbv2 $(TARGET_DIR)/usr/bin/
endef

$(eval $(cmake-package))
