#!/bin/bash

[ "$1" != "start" ] && exit

. /recalbox/scripts/recalbox-utils.sh

do_start() {
  local STEP=$(getStepNumber)

  # Cases - Don't try to detect if already done or if recalbox rgb dual is plugged
  if [ "$STEP" != "1" ] && ! isRecalboxRGBDual; then
    python /recalbox/system/hardware/case/manage.pyc "" 1 1 0
    # let S05hardware do its job if no case found here
    mount -o remount,rw /boot
    sed -i -E 's/^(case=none:0)/;\1/' /boot/recalbox-boot.conf
  fi

}

do_start
