#!/bin/ash

# Main
if [ "$1" == "start" ]; then

  INIT_SCRIPT=$(basename "$0")

  # GPI case? Deactivate HDMI to save energy
  case=$(sed -n 's/^case=\(.*\)/\1/p' /boot/recalbox-boot.conf)
  if [ "${case}" = "GPiV1:1" ]; then
    tvservice -o
  fi

  # Video cards
  if [ "$(uname -m)" == "x86_64" ]; then
    /recalbox/system/hardware/videocard/nvidia-install
  fi

  # Cases - Don't try to detect if already done or if recalbox rgb dual is plugged
  if ! grep -q "^\s*case=.*:1\s*$" /boot/recalbox-boot.conf && ! lsmod | grep -q "^recalboxrgbdual";then
    sleep 1
    udevadm settle --timeout=30
    python /recalbox/system/hardware/case/manage.pyc "" 1 1 0
  fi

  # Force enable DRM connectors
  ( /usr/bin/kms-enabler >/dev/null 2>&1 ) &

  # Installation image
  if [ -f /tmp/.install.sh ]; then
    ( /tmp/.install.sh initialize ) &
  fi
fi
