#!/bin/ash

# Main
if [ "$1" == "start" ]; then

  INIT_SCRIPT=$(basename "$0")

  # GPI case? Deactivate HDMI to save energy
  case=$(sed -n 's/^case=\(.*\)/\1/p' /boot/recalbox-boot.conf)
  if [ "${case}" = "GPiV1:1" ]; then
    recallog -s "${INIT_SCRIPT}" -t GPI "GPi case detected: turning HDMI off"
    tvservice -o
  fi

  # Video cards
  if [ "$(uname -m)" == "x86_64" ]; then
    /recalbox/system/hardware/videocard/nvidia-install
  fi

  # Cases - Don't try to detect if already done
  grep -q "^\s*case=.*:1\s*$" /boot/recalbox-boot.conf || python /recalbox/system/hardware/case/manage.pyc "" 1 1 0

  # Installation image
  if [ -f /tmp/.install.sh ]; then
    ( /tmp/.install.sh initialize ) &
  fi
fi
