#!/bin/sh
#
# Starts pulseaudio.
#


start() {
	printf "Starting pulseaudio: "
	umask 077
	start-stop-daemon -S -b -m -p /var/run/pulse.pid -x \
		/usr/bin/pulseaudio -- \
		--exit-idle-time=-1 --log-target=syslog
	echo "OK"
}
stop() {
	printf "Saving configuration: "
	echo ".include /etc/pulse/default.pa" >/overlay/.configs/pulse/default.pa
	pacmd dump |grep -E '(set-default-sink|set-card-profile)' >>/overlay/.configs/pulse/default.pa && echo "OK" || echo "KO"
	printf "Stopping pulseaudio: "
	start-stop-daemon -K -p /var/run/pulse.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

