#!/bin/bash
# vim: syntax=bash
# vim: filetype=sh

if [ "$1" != "start" ]; then
  exit 0
fi


INTERNALDEVICE=$(/recalbox/scripts/recalbox-part.sh "share_internal")
ARCH=$(cat /recalbox/recalbox.arch)
INIT_SCRIPT=$(basename "$0")
FIRSTTIMEFLAG=/overlay/.configs/firsttimevideo

source /recalbox/scripts/recalbox-boot-media.sh

# first boot or upgrade
if mediaShouldIgnoreSplash || [ ! -e "$INTERNALDEVICE" ] || ls /boot/update/recalbox-*.img.xz >/dev/null 2>&1 ; then
  recallog -s "${INIT_SCRIPT}" -t "INSTALL" "Install in progress. Don't play boot video"
  exit 0
fi

## Global variables ##
systemsetting="recalbox_settings"
machineArch=$(arch)

# define some paths
originalVideoPath="/recalbox/system/resources/splash"
originalSmallVideoPath="${originalVideoPath}/240p"
customVideoPath="/overlay/bootvideos"
firstTimeVideo=introRecalboxElectron-1080-Normed-12dB.mp4


## -1 : Video will be stopped when emulationstation is ready to start.
##  0 : All the video will be played before emulationstation start (default)
## >0 : Time the video will be played before emulationstation start (in seconds)
timeout="$($systemsetting -command load -key system.splash.length -source /boot/recalbox-backup.conf)"
# in specific case, force playing for 20s
if [ -z "${timeout}" ] || [ "${timeout}" -eq 0 ] || [ "${timeout}" -lt -1 ]; then
  videoLength=20
else
  videoLength="$timeout"
fi


# selectVideo
#   takes no argument and outputs a random video from those available
selectVideo() {
  # What to play?
  local videoSearchPath=()
  local whatToPlay
  local videos
  local num_videos
  if isFirstTime; then
    mediaIsLowDef \
        && echo "${originalSmallVideoPath}/${firstTimeVideo}" \
        || echo "${originalVideoPath}/${firstTimeVideo}"
    return 0
  fi
  whatToPlay="$($systemsetting -command load -key system.splash.select -source /boot/recalbox-backup.conf)"
  if [ "$whatToPlay" != "all" ] && [ "$whatToPlay" != "recalbox" ] && [ "$whatToPlay" != "custom" ] ; then whatToPlay="all" ; fi

  if [ "$whatToPlay" = "all" ] || [ "$whatToPlay" = "recalbox" ]; then
    [ -n "${LOWDEF}" ] && videoSearchPath+=("$originalSmallVideoPath") || videoSearchPath+=("$originalVideoPath")
  fi
  if [ "$whatToPlay" = "all" ] || [ "$whatToPlay" = "custom" ]; then
    videoSearchPath+=("$customVideoPath")
  fi

  # lookup selected directories and put it in videos var
  mapfile -t videos < <(find "${videoSearchPath[@]}" -maxdepth 1 \( -name "*.mp4" -o -name "*.avi" -o -name "*.mkv" \))
  # get number of available videos
  num_videos=${#videos[*]}
  # select one randomly
  echo "${videos[$((RANDOM%num_videos))]}"
}

# isFirstTime
#   takes no argument and return 0 if its first boot or update
isFirstTime() {
  local oldValue
  local newValue
  newValue=$(cat /recalbox/recalbox.version)
  if [ -f "$FIRSTTIMEFLAG" ]; then
    oldValue=$(cat $FIRSTTIMEFLAG)
    if [ "$oldValue" = "$newValue" ]; then
      return 1
    fi
  fi
  echo "$newValue" >"$FIRSTTIMEFLAG"
  return 0
}

## Main ##

startMpvQueue
mediaPlaySplash "$(selectVideo)" "${videoLength}"

exit 0