#!/bin/sh

case "$1" in
	start)
		recallog "Starting connman"
		printf "Starting connman ... "
		start-stop-daemon -S -q -m -b -p /var/run/connmand.pid --exec /usr/sbin/connmand -- -n
		echo "done."
		;;
	stop)
		recallog "Stopping connman"
		printf "Stopping connman ..."
		start-stop-daemon -K -q -p /var/run/connmand.pid
		echo "done."
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac
