#!/bin/bash

# Function to create connmann wifi profiles based on user settings

rb_wifi_boot_configure() {
        [ "$1" = "1" ] && X="" || X="$1"
        settings_ssid=`cat /tmp/wifi.conf|awk "/wifi${X}.ssid/"|sed "s/wifi${X}.ssid=//g"`
        settings_key=`cat /tmp/wifi.conf|awk "/wifi${X}.key/"|sed "s/wifi${X}.key=//g"`
        settings_file="/var/lib/connman/recalbox_wifi${X}.config"
        [ "$1" = "1" ] && settings_name="default" || settings_name="${X}"

        if [[ "$settings_ssid" != "" ]] ;then
        mkdir -p "/var/lib/connman"
        cat > "${settings_file}" <<EOF
[global]
Name=recalbox

[service_recalbox_${settings_name}]
Type=wifi
Name=${settings_ssid}
EOF
        if test "${settings_key}" != ""
        then
            settings_key_dec=$(/recalbox/scripts/recalbox-encode.sh decode "${settings_key}")
            echo "Passphrase=${settings_key_dec}" >> "${settings_file}"
	fi
    fi
}

# Main

case "$1" in
  start)
	if [ ! -f /tmp/wifi.conf ]
	then
		cat /boot/recalbox-boot.conf | awk '!/^;?wifi/' > /tmp/recalbox-boot.conf
		cat /boot/recalbox-boot.conf | awk '/^;?wifi/' > /tmp/wifi.conf
		mount -o remount,rw /boot
		mv /tmp/recalbox-boot.conf /boot/recalbox-boot.conf
		mount -o remount,ro /boot
	fi

	for i in {1..3}; do
		rb_wifi_boot_configure $i&
	done

        sleep 1 # wait a bit, otherwise, connman is not really started
	/usr/bin/connmanctl enable wifi || exit 1
	/usr/bin/connmanctl scan   wifi || exit 1
	if [ -f /tmp/wifi.conf ]
	then
		rm /tmp/wifi.conf
	fi
	;;
  stop)
	;;
  *)
esac

exit $?
