#!/bin/sh

# in some situations (emmc, ssd...) emulationstation can load really fast,
# so wait for splash to finish before launching ES

wait_splash_end() {
	systemsetting="recalbox_settings"

	videoLength="`$systemsetting -command load -key system.splash.length -source /boot/recalbox-backup.conf`"
	if [ ${videoLength} -ne 0 ] ; then

		mp_pid=$(pgrep -f S06splash)
		while kill -0 $mp_pid 2>/dev/null; do
			sleep 1
		done
	fi
}

case "$1" in
	start)
		wait_splash_end
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

exit 0
