#!/bin/bash

if test "$1" != "start"
then
  exit 0
fi

UPDATEFILE="rbx_no_upgrade"

for file in /boot/update/recalbox-*.img.xz; do
  if [[ -f $file ]]; then
    UPDATEFILE=${file}
    UPDATEFILE_UNCOMPRESSED=${file::-3}
    break
  fi
done

if test -e "${UPDATEFILE}"; then
  recallog -f upgrade.log "upgrade found! moving ${UPDATEFILE} to SHARE as $(basename "${UPDATEFILE_UNCOMPRESSED}")"
  killall S06splash
  fbv2 -f -i /recalbox/system/resources/offline-install-0.jpg
  unxz -c "${UPDATEFILE}" >"/recalbox/share/system/upgrade/$(basename "$UPDATEFILE_UNCOMPRESSED")"
  mount -o remount,rw /boot
  rm "${UPDATEFILE}"
  mount -o remount,ro /boot
  ( exec /recalbox/scripts/upgrade/recalbox-squashfs-upgrade.sh )
  exit 0
fi
