#!/bin/sh

if test "$1" == "start"
then
  	python2.7 /recalbox/system/hardware/case/manage.pyc "" 1 1 1
	# Installation image
	if [ -f /tmp/.install.sh ]; then
	    ( /tmp/.install.sh finalize ) &
	fi
fi

