#!/bin/bash

# This file runs migration scripts ONCE
## Migration type will save the migration stamp will be save in BOOT or SHARE
## Migrations will NOT be done on fresh install

# Run this script on startup only
if [[ $1 != "start" ]]; then
  exit 0
fi

# Useful global variables
INIT_SCRIPT=$(basename "$0")

##########################
###     Migrations     ###
##########################

recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Running MIGRATIONS..."
BOOT_TYPE="boot"
SHARE_TYPE="share"

declare -A MIGRATION_FILES=(
    [$BOOT_TYPE]="/boot/.system-migrations"
    [$SHARE_TYPE]="/recalbox/share/system/.system-migrations"
)
echo "${MIGRATION_FILES['boot']}"
function migrationDone {
    local MIGRATIONTYPE="${1}"
    local MIGRATION="${2}"
    if [[ "${MIGRATIONTYPE}" == "${BOOT_TYPE}" ]];then
        mount -o remount,rw /boot
        echo "${MIGRATION}" >> "${MIGRATION_FILES[${BOOT_TYPE}]}"
        mount -o remount,ro /boot
    elif [[ "${MIGRATIONTYPE}" == "${SHARE_TYPE}" ]];then
        echo "${MIGRATION}" >> "${MIGRATION_FILES[${SHARE_TYPE}]}"
    fi
}

function shouldMigrate {
    local MIGRATIONTYPE="${1}"
    local MIGRATION="${2}"
    # The file does not exists, we should create it
    if [ -n "${MIGRATION_FILES[${MIGRATIONTYPE}]}" ] && [ ! -f "${MIGRATION_FILES[${MIGRATIONTYPE}]}" ]; then
        recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Creating migration stamp file ${MIGRATION_FILES[${MIGRATIONTYPE}]}"
        migrationDone "${MIGRATIONTYPE}" "#Migrations"
    fi
    # On first install we should not migrate
    # so we save the migration as done and don't let the migration happen
    if [ -f "/tmp/.first-install" ]; then
        recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "First install, ignoring ${MIGRATION}"
        migrationDone "${MIGRATIONTYPE}" "${MIGRATION}"
        return 1
    fi

    ! grep -q "${MIGRATION}" "${MIGRATION_FILES[${MIGRATIONTYPE}]}"
}

function runMigrations {
    if shouldMigrate "${BOOT_TYPE}" "9.1-hdmi-hotplug"; then
        # HDMI hotplug options should be removed from recalbox-user-config.txt for all
        # See https://gitlab.com/recalbox/recalbox/-/merge_requests/2514
        source /recalbox/scripts/recalbox-utils.sh
        if [[ $(getArchName) =~ rpi* ]] && [ -f "/boot/recalbox-user-config.txt" ];then
            recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Running migration 9.1-hdmi-hotplug"
            mount -o remount,rw /boot
            sed -i "s/hdmi_force_hotplug=./hdmi_force_hotplug=0/g" "/boot/recalbox-user-config.txt"
            mount -o remount,ro /boot
            migrationDone "${BOOT_TYPE}" "9.1-hdmi-hotplug"
            reboot
            return
        else
            migrationDone "${BOOT_TYPE}" "9.1-hdmi-hotplug"
        fi
    fi
}

runMigrations