#!/bin/sh
#
#

systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"

PIDFILE=/var/run/emulationstation.pid
ESBIN=/usr/bin/emulationstation

case "$1" in
  start)
	enabled="`$systemsetting -command load -key system.es.atstartup`"
	videoMode="`$systemsetting -command load -key system.es.videomode`"
	if [ "$enabled" != "0" ];then

		OUT=/recalbox/share
		SHARECONFFILE="/boot/recalbox-boot.conf"
		INTERNALDEVICE=$(/recalbox/scripts/recalbox-part.sh "share_internal")
		SHAREDEVICE=`cat ${SHARECONFFILE} | grep "sharedevice=" | head -n1 | cut -d'=' -f2`
		NBSHARE=`df | grep "/recalbox/share$" | wc -l`

		[[ "$?" -ne "0" || "$SHAREDEVICE" == "" ]] && SHAREDEVICE=INTERNAL

		# If we're on an external share and the .userdefined file is not here, let's wait for it before launching ES
		if [[ ( ! -e "$OUT"/.userdefined ) && ( ( "$SHAREDEVICE" != "INTERNAL" && "$SHAREDEVICE" != "NETWORK" ) || ( "$SHAREDEVICE" == "NETWORK" && "$NBSHARE" -gt 1 ) ) ]]
		then
			while [ ! -e "$OUT"/.userdefined ]; do
				echo "waiting for ${OUT}/.userdefined"
				sleep 1
			done
		fi
		/recalbox/scripts/showlogo.sh & # In case the logo has been removed, let's put it back again
		echo $videoMode | grep -qE "(CEA|DMT) [0-9]{1,2} (HDMI|DVI)"
		[ $? = "0" ] && tvservice -e "$videoMode"
		settings_lang="`$systemsetting -command load -key system.language`"
		recallog "starting emulationstation with lang = $settings_lang"
		HOME=/recalbox/share/system LANG="${settings_lang}.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_VIDEO_EGL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 start-stop-daemon -S -q -m -p /var/run/emulationstation.pid  --exec /usr/bin/emulationstation -- --debug &
	fi
	;;
  stop)
	recallog "Stopping Emulationstation"
	start-stop-daemon -K -q -p "${PIDFILE}"
	;;
  restart|reload)
	"$0" stop
	if [ -f "${PIDFILE}" ] ; then
		ESPID=`cat /var/run/emulationstation.pid 2>/dev/null`
		while `"$0" status > /dev/null` ; do
			sleep 0.1
		done
	fi
	"$0" start
	;;
  status)
	ESPID=`cat ${PIDFILE} 2>/dev/null`
	if [ -f "${PIDFILE}" ] && `ps | grep -qE "^[[:space:]]*${ESPID}"` ; then
		echo "Emulationstation is running (pid `cat /var/run/emulationstation.pid`)"
		exit 0
	else
		echo "Emulationstation is stopped"
		exit 1
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
