#!/bin/sh

if test "$1" != "start"
then
  exit 0
fi

systemsetting="recalbox_settings"
MASTERPASSWD="recalboxroot"

# write the /etc/shadow file
SHADOWPASSWD=$(openssl passwd -1 "${MASTERPASSWD}")
echo "root:${SHADOWPASSWD}:::::::" > /run/recalbox.shadow

# secure samba
mkdir -p "/var/lib/samba/private"
(echo "${MASTERPASSWD}"; echo "${MASTERPASSWD}") | smbpasswd -a root
