#!/bin/sh
#
# Initialize a dropbear host key
#
# The SSH daemon dropbear generate its host key on first connection
# The host key used to point to /recalbox/share/system/ssh (using a symbolic link)
# dropbear makes use of link() function when generating its host key but
# it's not implemented in exfat
# This script will initialize a host key into the overlay
#

if [ "$1" != "start" ]; then
  exit 0
fi

# simple exit if key already generated
[ -f /etc/dropbear/dropbear_ecdsa_host_key ] && exit 0

echo -n "Generating dropbear host key: "

# generate a key
mount -o remount,rw /
dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key >/dev/null && echo "done" || echo "failed"
mount -o remount,ro /

exit 0
