################################################################################
#
# recalbox-romfs-amiga1200
#
################################################################################

# Package generated with :
# ./scripts/linux/empack.py --force --system amiga1200 --extension '.adf .adz .ipf .lha .lhz .lzx .zip .rp9 .dms .fdi .hdf .hdz .m3u' --fullname 'Amiga 1200' --platform amiga --theme amiga1200 1:amiberry:amiberry:BR2_PACKAGE_AMIBERRY 2:libretro:puae:BR2_PACKAGE_LIBRETRO_UAE 3:libretro:uae4arm:BR2_PACKAGE_LIBRETRO_UAE4ARM

# Name the 3 vars as the package requires
RECALBOX_ROMFS_AMIGA1200_SOURCE = 
RECALBOX_ROMFS_AMIGA1200_SITE = 
RECALBOX_ROMFS_AMIGA1200_INSTALL_STAGING = NO
# Set the system name
SYSTEM_NAME_AMIGA1200 = amiga1200
SYSTEM_XML_AMIGA1200 = $(@D)/$(SYSTEM_NAME_AMIGA1200).xml
# System rom path
SOURCE_ROMDIR_AMIGA1200 = $(RECALBOX_ROMFS_AMIGA1200_PKGDIR)/roms

# CONFIGGEN_STD_CMD is defined in recalbox-romfs, so take good care that
# variables are global across buildroot


ifneq ($(BR2_PACKAGE_AMIBERRY)$(BR2_PACKAGE_LIBRETRO_UAE)$(BR2_PACKAGE_LIBRETRO_UAE4ARM),)
define CONFIGURE_MAIN_AMIGA1200_START
	$(call RECALBOX_ROMFS_CALL_ADD_SYSTEM,$(SYSTEM_XML_AMIGA1200),Amiga 1200,$(SYSTEM_NAME_AMIGA1200),.adf .adz .ipf .lha .lhz .lzx .zip .rp9 .dms .fdi .hdf .hdz .m3u,amiga,amiga1200)
endef

ifneq ($(BR2_PACKAGE_AMIBERRY)$(BR2_PACKAGE_LIBRETRO_UAE)$(BR2_PACKAGE_LIBRETRO_UAE4ARM),)
define CONFIGURE_AMIGA1200_AMIBERRY_START
	$(call RECALBOX_ROMFS_CALL_START_EMULATOR,$(SYSTEM_XML_AMIGA1200),amiberry)
endef
ifeq ($(BR2_PACKAGE_AMIBERRY),y)
define CONFIGURE_AMIGA1200_AMIBERRY_AMIBERRY_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_AMIGA1200),amiberry,1)
endef
endif

define CONFIGURE_AMIGA1200_AMIBERRY_END
	$(call RECALBOX_ROMFS_CALL_END_EMULATOR,$(SYSTEM_XML_AMIGA1200))
endef
endif

ifneq ($(BR2_PACKAGE_AMIBERRY)$(BR2_PACKAGE_LIBRETRO_UAE)$(BR2_PACKAGE_LIBRETRO_UAE4ARM),)
define CONFIGURE_AMIGA1200_LIBRETRO_START
	$(call RECALBOX_ROMFS_CALL_START_EMULATOR,$(SYSTEM_XML_AMIGA1200),libretro)
endef
ifeq ($(BR2_PACKAGE_LIBRETRO_UAE),y)
define CONFIGURE_AMIGA1200_LIBRETRO_PUAE_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_AMIGA1200),puae,2)
endef
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_UAE4ARM),y)
define CONFIGURE_AMIGA1200_LIBRETRO_UAE4ARM_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_AMIGA1200),uae4arm,3)
endef
endif

define CONFIGURE_AMIGA1200_LIBRETRO_END
	$(call RECALBOX_ROMFS_CALL_END_EMULATOR,$(SYSTEM_XML_AMIGA1200))
endef
endif



define CONFIGURE_MAIN_AMIGA1200_END
	$(call RECALBOX_ROMFS_CALL_END_SYSTEM,$(SYSTEM_XML_AMIGA1200),$(SOURCE_ROMDIR_AMIGA1200),$(@D))
endef
endif

define RECALBOX_ROMFS_AMIGA1200_CONFIGURE_CMDS
	$(CONFIGURE_MAIN_AMIGA1200_START)
	$(CONFIGURE_AMIGA1200_AMIBERRY_START)
	$(CONFIGURE_AMIGA1200_AMIBERRY_AMIBERRY_DEF)
	$(CONFIGURE_AMIGA1200_AMIBERRY_END)
	$(CONFIGURE_AMIGA1200_LIBRETRO_START)
	$(CONFIGURE_AMIGA1200_LIBRETRO_PUAE_DEF)
	$(CONFIGURE_AMIGA1200_LIBRETRO_UAE4ARM_DEF)
	$(CONFIGURE_AMIGA1200_LIBRETRO_END)
	$(CONFIGURE_MAIN_AMIGA1200_END)
endef

$(eval $(generic-package))
