################################################################################
#
# recalbox-rockchip-mali-bifrost-vulkan
#
################################################################################

RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_VERSION = r13p0
RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_SOURCE = rk3326_$(RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_VERSION)_gbm_with_vulkan_and_cl.zip
RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_SITE = https://dn.odroid.com/RK3326/ODROID-GO-Advance
RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_STAGING = YES
RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_PROVIDES = libegl libgles libgbm
RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_DEPENDENCIES = recalbox-rockchip-mali

RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_LICENSE = COPYRIGHT

RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_LIB_FILE = libmali.so_rk3326_gbm_arm64_$(RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_VERSION)_with_vulkan_and_cl

define RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_EXTRACT_CMDS
	unzip $(RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_DL_DIR)/$(RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_SOURCE) -d $(@D)
endef

define RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_CMDS
	$(INSTALL) -D $(@D)/$(RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_LIB_FILE) $(1)/usr/lib/libmali.so.1.9.0
endef

define RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_TARGET_CMDS
	$(call RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_CMDS,$(TARGET_DIR))
endef

define RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_STAGING_CMDS
	$(call RECALBOX_ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_CMDS,$(STAGING_DIR))
endef

$(eval $(generic-package))
