################################################################################
#
# SWANSTATION
#
################################################################################

#Commit 23/05/2021
LIBRETRO_SWANSTATION_VERSION = a39c7512c47c125f554c4e4725217c16628683e4
LIBRETRO_SWANSTATION_SITE = $(call github,libretro,swanstation,$(LIBRETRO_SWANSTATION_VERSION))
LIBRETRO_SWANSTATION_LICENSE = GPL-3.0
LIBRETRO_SWANSTATION_LICENSE_FILES = LICENSE

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
LIBRETRO_SWANSTATION_DEPENDENCIES += libgles
endif

LIBRETRO_SWANSTATION_CONF_OPTS=-DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRETRO_CORE=ON -DBUILD_SHARED_LIBS=FALSE

define LIBRETRO_SWANSTATION_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/swanstation_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/swanstation_libretro.so
endef

LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_SO)"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_SO)"
LIBRETRO_SWANSTATION_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_SO)"

$(eval $(cmake-package))
