#!/bin/bash

# Looks for nvidia drivers in /usr/lib/extra/
# one directory per version, eg: nvidia-515.1

# A controller may be supported in many versions.
# One should make sure driver are read from newer to older
# in order to always have newer driver version first

# exit if already installed

INIT_SCRIPT=$(basename "$0")

exit_if_nvidia_installed() {
  [ -f /etc/modprobe.d/blacklist.conf ] && grep -q -E '^blacklist nouveau' /etc/modprobe.d/blacklist.conf && exit 0
}

log_info() {
  while read -r line; do
    log INFO "$line"
  done
}

log_error() {
  while read -r line; do
    log ERROR "$line"
  done
}

log() {
  /usr/bin/recallog -s "${INIT_SCRIPT}" -t "$1" -e "$2"
}

exec 1> >(log_info)
exec 2> >(log_error)

cd "$(dirname "$0")"

for driver_version in $(find /usr/lib/extra/ -name "nvidia-*" -maxdepth 1 | cut -d - -f 2 | sort -n -r); do
  exit_if_nvidia_installed # exit if already installed or driver installation succeeded
  python main.py --version "$driver_version"
done
