#!/bin/bash

##nvidia-driver installation##

## nvidia select after first boot for blacklist nouveau and install all libraries
lspciOutput=$(lspci)
##check gpu nvidia
pci=($(echo "${lspciOutput}" |grep "NVIDIA Corporation" |grep -vE "Audio device" |awk '{print $8 $9 $10 }'))
##check the compatibility of the graphics card with the driver version "390.116"
suportList=($(echo "${lspciOutput}" |grep -rni "${pci}" /recalbox/system/hardware/videocard/nvidiacheckcompatibility.txt))
##nouveau conflict with nvidia-drm
blacklistFile="/etc/modprobe.d/blacklist.conf"
##check if driver 'nouveau' blacklist first boot
nouveauCheck=($(grep -r 'blacklist nouveau' "${blacklistFile}"))
##nvdia libs in 'extra' folder
libs="/usr/lib"
xorgModules="${libs}"/xorg/modules
nvidiaVersion=($(ls "${libs}"/extra/ | grep libEGL_nvidia.so |cut -d . -f 3,4))

if [ -n "${pci}" ]; then
  echo "graphics card model :'${pci}'"
else 
  echo "generic driver !"
fi

if [ -n "${pci}" ] && [ -n "${suportList}" ]; then
  echo "graphics card compatible with version 390.116"
  if [ -z "${nouveauCheck}" ]; then
    mount -o remount, rw /
    echo "blacklist nouveau" >> "${blacklistFile}"
    echo "options nvidia-drm modeset=1" >> "/etc/modprobe.d/nvidia-drm.conf"
    echo "nouveau blacklisted"

    echo "Install libraries"
    chmod +x "${xorgModules}"/extra/libnvidia*
    cp "${xorgModules}"/extra/libnvidia-wfb.so."${nvidiaVersion}" "${xorgModules}"/libnvidia-wfb.so
    chmod +x "${xorgModules}"/extra/drivers/nvidia*
    cp "${xorgModules}"/extra/drivers/nvidia_drv.so "${xorgModules}"/drivers/nvidia_drv.so
    chmod +x "${xorgModules}"/extra/extensions/libglx.so.*
    cp "${xorgModules}"/extra/extensions/libglx.so."${nvidiaVersion}" "${xorgModules}"/extensions/libglx.so."${nvidiaVersion}"
    cd "${xorgModules}"/extensions/
     ln -sf libglx.so."${nvidiaVersion}" libglx.so

    chmod -x "${libs}"/extra/lib*
    cp "${libs}"/extra/* "${libs}"/
    cd "${libs}"/

    ln -sf libEGL.so.1.1.0 libEGL.so.1
        ln -sf libEGL.so.1.1.0 libEGL.so
    ln -sf libEGL_nvidia.so.${nvidiaVersion} libEGL_nvidia.so.0
        ln -sf libGLX_nvidia.so.${nvidiaVersion} libGLX_nvidia.so
    ln -sf libGL.so.${nvidiaVersion} libGL.so.1
        ln -sf libGL.so.${nvidiaVersion} libGL.so
    ln -sf libGLESv1_CM.so.1.2.0 libGLESv1_CM.so.1
        ln -sf libGLESv1_CM.so.1.2.0 libGLESv1_CM.so
    ln -sf libGLESv1_CM_nvidia.so.${nvidiaVersion} libGLESv1_CM_nvidia.so.1
        ln -sf libGLESv1_CM_nvidia.so.${nvidiaVersion} libGLESv1_CM_nvidia.so
    ln -sf libGLESv2.so.2.1.0 libGLESv2.so.2
        ln -sf libGLESv2.so.2.1.0 libGLESv2.so
    ln -sf libGLESv2_nvidia.so.${nvidiaVersion} libGLESv2_nvidia.so.2
        ln -sf libGLESv2_nvidia.so.${nvidiaVersion} libGLESv2_nvidia.so
    ln -sf libGLX.so.0 libGLX.so
    ln -sf libGLX_nvidia.so.${nvidiaVersion} libGLX_nvidia.so.0
        ln -sf libGLX_nvidia.so.${nvidiaVersion} libGLX_nvidia.so
    ln -sf libGLdispatch.so.0 libGLdispatch.so
    ln -sf libOpenCL.so.1.0.0 libOpenCL.so.1
        ln -sf libOpenCL.so.1.0.0 libOpenCL.so
    ln -sf libvdpau_nvidia.so.${nvidiaVersion} libvdpau_nvidia.so.1
        ln -sf libvdpau_nvidia.so.${nvidiaVersion} libvdpau_nvidia.so
    ln -sf libnvidia-egl-wayland.so.1.0.2 libnvidia-egl-wayland.so.1
        ln -sf libnvidia-egl-wayland.so.1.0.2 libnvidia-egl-wayland.so
    ln -sf libnvidia-eglcore.so.${nvidiaVersion} libnvidia-eglcore.so
    ln -sf libnvidia-glcore.so.${nvidiaVersion} libnvidia-glcore.so
    ln -sf libnvidia-glsi.so.${nvidiaVersion} libnvidia-glsi.so
    ln -sf libnvidia-ml.so.${nvidiaVersion} libnvidia-ml.so.1
        ln -sf libnvidia-ml.so.${nvidiaVersion} libnvidia-ml.so
    ln -sf libnvidia-tls.so.${nvidiaVersion} libnvidia-tls.so
    ln -sf libcuda.so.${nvidiaVersion} libcuda.so
    ln -sf libnvcuvid.so.${nvidiaVersion} libnvcuvid.so
    ln -sf libnvidia-compiler.so.${nvidiaVersion} libnvidia-compiler.so
    ln -sf libnvidia-encode.so.${nvidiaVersion} libnvidia-encode.so
    ln -sf libnvidia-fatbinaryloader.so.${nvidiaVersion} libnvidia-fatbinaryloader.so
    ln -sf libnvidia-opencl.so.${nvidiaVersion} libnvidia-opencl.so
    ln -sf libnvidia-ptxjitcompiler.so.${nvidiaVersion} libnvidia-ptxjitcompiler.so
    ln -sf libnvidia-tls.so.${nvidiaVersion} libnvidia-tls.so
  else
    echo "'nouveau' is already blacklisted"
  fi
else
    echo "Nvidia gpu not found."
fi
