################################################################################
#
# Recalbox System
#
################################################################################

RECALBOX_SYSTEM_SOURCE =

RECALBOX_SYSTEM_VERSION = 0.2
RECALBOX_SYSTEM_LICENSE = COPYRIGHT

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4),y)
RECALBOX_SYSTEM_PLATFORM=rpi4
RECALBOX_SYSTEM_RECALBOX_CONF=rpi4
RECALBOX_SYSTEM_FIRMWAREDIR=rpi-firmware
RECALBOX_SYSTEM_DEPENDENCIES=rpi-firmware
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI3),y)
RECALBOX_SYSTEM_PLATFORM=rpi3
RECALBOX_SYSTEM_RECALBOX_CONF=rpi3
RECALBOX_SYSTEM_FIRMWAREDIR=rpi-firmware
RECALBOX_SYSTEM_DEPENDENCIES=rpi-firmware
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDXU4),y)
RECALBOX_SYSTEM_PLATFORM=odroidxu4
RECALBOX_SYSTEM_RECALBOX_CONF=odroidxu4
RECALBOX_SYSTEM_FIRMWAREDIR=odroidxu4-firmware
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
RECALBOX_SYSTEM_PLATFORM=odroidgo2
RECALBOX_SYSTEM_RECALBOX_CONF=odroidgo2
RECALBOX_SYSTEM_FIRMWAREDIR=odroidgo2-firmware
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_X86),y)
RECALBOX_SYSTEM_PLATFORM=x86
RECALBOX_SYSTEM_RECALBOX_CONF=x86
RECALBOX_SYSTEM_FIRMWAREDIR=pc-boot
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_X86_64),y)
RECALBOX_SYSTEM_PLATFORM=x86_64
RECALBOX_SYSTEM_RECALBOX_CONF=x86_64
RECALBOX_SYSTEM_FIRMWAREDIR=pc-boot
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI2),y)
RECALBOX_SYSTEM_PLATFORM=rpi2
RECALBOX_SYSTEM_RECALBOX_CONF=rpi2
RECALBOX_SYSTEM_FIRMWAREDIR=rpi-firmware
RECALBOX_SYSTEM_DEPENDENCIES=rpi-firmware
else
RECALBOX_SYSTEM_PLATFORM=rpi1
RECALBOX_SYSTEM_RECALBOX_CONF=rpi1
RECALBOX_SYSTEM_FIRMWAREDIR=rpi-firmware
RECALBOX_SYSTEM_DEPENDENCIES=rpi-firmware
endif

ifeq ($(BR2_PACKAGE_RPI_FIRMWARE),y)
define RECALBOX_SYSTEM_INSTALL_RPI_CONFIG
	$(INSTALL) -D -m 0644 $(RECALBOX_SYSTEM_PKGDIR)/config.txt $(BINARIES_DIR)/$(RECALBOX_SYSTEM_FIRMWAREDIR)/config.txt
	$(INSTALL) -D -m 0644 $(RECALBOX_SYSTEM_PKGDIR)/recalbox-user-config.txt $(BINARIES_DIR)/$(RECALBOX_SYSTEM_FIRMWAREDIR)/recalbox-user-config.txt
	$(INSTALL) -D -m 0644 $(RECALBOX_SYSTEM_PKGDIR)/recalbox-oc-config.txt $(BINARIES_DIR)/$(RECALBOX_SYSTEM_FIRMWAREDIR)/recalbox-oc-config.txt
endef
endif

define RECALBOX_SYSTEM_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/recalbox/
	echo -n "$(RECALBOX_SYSTEM_PLATFORM)" > $(TARGET_DIR)/recalbox/recalbox.arch
	mkdir -p $(TARGET_DIR)/recalbox/share_init/system
	cp $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/recalbox.conf $(TARGET_DIR)/recalbox/share_init/system
	cp $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/recalbox.conf $(TARGET_DIR)/recalbox/share_init/system/recalbox.conf.template
	# recalbox-boot.conf
	$(INSTALL) -D -m 0644 $(RECALBOX_SYSTEM_PKGDIR)/recalbox-boot.conf $(BINARIES_DIR)/$(RECALBOX_SYSTEM_FIRMWAREDIR)/recalbox-boot.conf
	$(RECALBOX_SYSTEM_INSTALL_RPI_CONFIG)
	[[ -f $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/pre-upgrade.sh ]] && $(INSTALL) -D -m 0755 $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/pre-upgrade.sh $(BINARIES_DIR)/pre-upgrade.sh || :
	[[ -f $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/boot.ppm ]] && $(INSTALL) -D -m 0755 $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/boot.ppm $(BINARIES_DIR)/$(RECALBOX_SYSTEM_FIRMWAREDIR)/boot.ppm || :
	[[ -f $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/logo.bmp ]] && $(INSTALL) -D -m 0755 $(RECALBOX_SYSTEM_PKGDIR)/$(RECALBOX_SYSTEM_RECALBOX_CONF)/logo.bmp $(BINARIES_DIR)/$(RECALBOX_SYSTEM_FIRMWAREDIR)/logo.bmp || :
endef

$(eval $(generic-package))
