################################################################################
#
# FLYCAST
#
################################################################################

# Commit version of 2022/11/29
LIBRETRO_FLYCAST_VERSION = a40210c55c70604e012f6f330247910972972c34
LIBRETRO_FLYCAST_SITE = https://github.com/flyinghead/flycast.git
LIBRETRO_FLYCAST_SITE_METHOD=git
LIBRETRO_FLYCAST_GIT_SUBMODULES=y
LIBRETRO_FLYCAST_LICENSE = GPLv2
LIBRETRO_FLYCAST_DEPENDENCIES = retroarch

LIBRETRO_FLYCAST_CONF_OPTS = -DLIBRETRO=ON -DUSE_OPENMP=ON -DBUILD_SHARED_LIBS=OFF

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_OPENGL=ON
else
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_OPENGL=OFF
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4),y)
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_GLES=ON -DUSE_GLES2=OFF -DUSE_OPENGL=ON
else
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_GLES=OFF -DUSE_GLES2=ON -DUSE_OPENGL=ON
endif
else
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_GLES=OFF -DUSE_GLES2=OFF
endif

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI1),y)
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_VIDEOCORE=OFF
endif

ifeq ($(BR2_PACKAGE_MESA3D_VULKAN_DRIVER),y)
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_VULKAN=ON
else
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_VULKAN=OFF
endif

LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_SO)"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_SO)"
LIBRETRO_FLYCAST_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="$(COMPILER_COMMONS_LDFLAGS_SO)"

define LIBRETRO_FLYCAST_INSTALL_TARGET_CMDS
        $(INSTALL) -D $(@D)/flycast_libretro.so \
                $(TARGET_DIR)/usr/lib/libretro/flycast_libretro.so
endef

$(eval $(cmake-package))