################################################################################
#
# recalbox-romfs-quake
#
################################################################################

# Package generated with :
# ./scripts/linux/empack.py --force --system quake --extension '.pak .PAK .pk3 .PK3 .zip .ZIP .7z .7Z' --fullname 'Quake' --platform quake --theme quake 1:libretro:tyrquake:BR2_PACKAGE_LIBRETRO_TYRQUAKE 2:libretro:vitaquake2:BR2_PACKAGE_LIBRETRO_VITAQUAKE2 3:libretro:vitaquake3:BR2_PACKAGE_LIBRETRO_VITAQUAKE3 4:libretro:vitavoyager:BR2_PACKAGE_LIBRETRO_VITAVOYAGER

# Name the 3 vars as the package requires
RECALBOX_ROMFS_QUAKE_SOURCE = 
RECALBOX_ROMFS_QUAKE_SITE = 
RECALBOX_ROMFS_QUAKE_INSTALL_STAGING = NO
# Set the system name
SYSTEM_NAME_QUAKE = quake
SYSTEM_XML_QUAKE = $(@D)/$(SYSTEM_NAME_QUAKE).xml
# System rom path
SOURCE_ROMDIR_QUAKE = $(RECALBOX_ROMFS_QUAKE_PKGDIR)/roms

# CONFIGGEN_STD_CMD is defined in recalbox-romfs, so take good care that
# variables are global across buildroot


ifneq ($(BR2_PACKAGE_LIBRETRO_TYRQUAKE)$(BR2_PACKAGE_LIBRETRO_VITAQUAKE2)$(BR2_PACKAGE_LIBRETRO_VITAQUAKE3)$(BR2_PACKAGE_LIBRETRO_VITAVOYAGER),)
define CONFIGURE_MAIN_QUAKE_START
	$(call RECALBOX_ROMFS_CALL_ADD_SYSTEM,$(SYSTEM_XML_QUAKE),Quake,$(SYSTEM_NAME_QUAKE),.pak .PAK .pk3 .PK3 .zip .ZIP .7z .7Z,quake,quake)
endef

ifneq ($(BR2_PACKAGE_LIBRETRO_TYRQUAKE)$(BR2_PACKAGE_LIBRETRO_VITAQUAKE2)$(BR2_PACKAGE_LIBRETRO_VITAQUAKE3)$(BR2_PACKAGE_LIBRETRO_VITAVOYAGER),)
define CONFIGURE_QUAKE_LIBRETRO_START
	$(call RECALBOX_ROMFS_CALL_START_EMULATOR,$(SYSTEM_XML_QUAKE),libretro)
endef
ifeq ($(BR2_PACKAGE_LIBRETRO_TYRQUAKE),y)
define CONFIGURE_QUAKE_LIBRETRO_TYRQUAKE_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_QUAKE),tyrquake,1)
endef
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VITAQUAKE3),y)
define CONFIGURE_QUAKE_LIBRETRO_VITAQUAKE3_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_QUAKE),vitaquake3,3)
endef
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VITAQUAKE2),y)
define CONFIGURE_QUAKE_LIBRETRO_VITAQUAKE2_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_QUAKE),vitaquake2,2)
endef
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_VITAVOYAGER),y)
define CONFIGURE_QUAKE_LIBRETRO_VITAVOYAGER_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_QUAKE),vitavoyager,4)
endef
endif

define CONFIGURE_QUAKE_LIBRETRO_END
	$(call RECALBOX_ROMFS_CALL_END_EMULATOR,$(SYSTEM_XML_QUAKE))
endef
endif



define CONFIGURE_MAIN_QUAKE_END
	$(call RECALBOX_ROMFS_CALL_END_SYSTEM,$(SYSTEM_XML_QUAKE),$(SOURCE_ROMDIR_QUAKE),$(@D))
endef
endif

define RECALBOX_ROMFS_QUAKE_CONFIGURE_CMDS
	$(CONFIGURE_MAIN_QUAKE_START)
	$(CONFIGURE_QUAKE_LIBRETRO_START)
	$(CONFIGURE_QUAKE_LIBRETRO_TYRQUAKE_DEF)
	$(CONFIGURE_QUAKE_LIBRETRO_VITAQUAKE3_DEF)
	$(CONFIGURE_QUAKE_LIBRETRO_VITAQUAKE2_DEF)
	$(CONFIGURE_QUAKE_LIBRETRO_VITAVOYAGER_DEF)
	$(CONFIGURE_QUAKE_LIBRETRO_END)
	$(CONFIGURE_MAIN_QUAKE_END)
endef

$(eval $(generic-package))
