################################################################################
#
# LIBRETRO PPSSPP
#
################################################################################

LIBRETRO_PPSSPP_VERSION = 47ff758af11369f1dc602ec39cc710f33ac44bc3
LIBRETRO_PPSSPP_SITE = git://github.com/hrydgard/ppsspp.git
LIBRETRO_PPSSPP_GIT_SUBMODULES=y
LIBRETRO_PPSSPP_DEPENDENCIES = ffmpeg snappy zip sdl2 libpng
LIBRETRO_PPSSPP_LICENSE = GPL-2.0
LIBRETRO_PPSSPP_LICENSE_FILES = LICENSE.TXT

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_XU4)$(BR2_PACKAGE_RECALBOX_TARGET_RPI4),y)
LIBRETRO_PPSSPP_PLATFORM=unix-gles
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4_64)$(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
LIBRETRO_PPSSPP_PLATFORM=arm64-gles
else
LIBRETRO_PPSSPP_PLATFORM=$(RETROARCH_LIBRETRO_PLATFORM)
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_PPSSPP_DEPENDENCIES += libgl
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
LIBRETRO_PPSSPP_DEPENDENCIES += libgles
endif

LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_NOLTO) -DEGL_NO_X11=1 -DMESA_EGL_NO_X11_HEADERS=1"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_NOLTO) -DEGL_NO_X11=1 -DMESA_EGL_NO_X11_HEADERS=1"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_NOLTO)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
# :: Options
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_FFMPEG=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_DISCORD=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_MINIUPNPC=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_SNAPPY=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_FFMPEG=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBZIP=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBSDL2=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBPNG=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_ZSTD=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_MINIUPNPC=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
# :: Frontends
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_QT_UI=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DMOBILE_DEVICE=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DHEADLESS=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUNITTEST=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DSIMULATOR=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DLIBRETRO=ON
# :: Environments
ifeq ($(BR2_arm)$(BR2_aarch64),y)
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_GLES2=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_EGL=ON
endif
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_FBDEV=OFF
ifeq ($(BR2_PACKAGE_XORG7),y)
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_X11_VULKAN=ON
else
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_X11_VULKAN=OFF
endif

define LIBRETRO_PPSSPP_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/lib/ppsspp_libretro.so $(TARGET_DIR)/usr/lib/libretro/ppsspp_libretro.so
	mkdir -p $(TARGET_DIR)/usr/share/ppsspp
	cp -R $(@D)/assets $(TARGET_DIR)/usr/share/ppsspp/PPSSPP
endef

$(eval $(cmake-package))
