################################################################################
#
# kodi python twitch script
#
################################################################################

KODI_SCRIPT_MODULE_PYTHON_TWITCH_RELEASE = matrix
KODI_SCRIPT_MODULE_PYTHON_TWITCH_VERSION = 3.0.0
KODI_SCRIPT_MODULE_PYTHON_TWITCH_PLUGIN_NAME = script.module.python.twitch
KODI_SCRIPT_MODULE_PYTHON_TWITCH_SOURCE = $(KODI_SCRIPT_MODULE_PYTHON_TWITCH_PLUGIN_NAME)-$(KODI_SCRIPT_MODULE_PYTHON_TWITCH_VERSION).zip
KODI_SCRIPT_MODULE_PYTHON_TWITCH_SITE = https://github.com/anxdpanic/$(KODI_SCRIPT_MODULE_PYTHON_TWITCH_PLUGINNAME)/releases/download/v$(KODI_SCRIPT_MODULE_PYTHON_TWITCH_VERSION)
KODI_SCRIPT_MODULE_PYTHON_TWITCH_LICENSE = GPL-3.0-only
KODI_SCRIPT_MODULE_PYTHON_TWITCH_LICENSE_FILES = $(KODI_SCRIPT_MODULE_PYTHON_TWITCH_PLUGIN_NAME)/LICENSES/GPL-3.0-only

KODI_SCRIPT_MODULE_PYTHON_TWITCH_TARGET_DIR=$(TARGET_DIR)/usr/share/kodi/addons

define KODI_SCRIPT_MODULE_PYTHON_TWITCH_EXTRACT_CMDS
	@unzip -q -o $(DL_DIR)/kodi-script-module-python-twitch/$(KODI_SCRIPT_MODULE_PYTHON_TWITCH_SOURCE) -d $(@D)
endef

define KODI_SCRIPT_MODULE_PYTHON_TWITCH_INSTALL_TARGET_CMDS
	@mkdir -p $(KODI_SCRIPT_MODULE_PYTHON_TWITCH_TARGET_DIR)
	@cp -r $(@D)/$(KODI_SCRIPT_MODULE_PYTHON_TWITCH_PLUGIN_NAME) $(KODI_SCRIPT_MODULE_PYTHON_TWITCH_TARGET_DIR)/
endef

$(eval $(generic-package))
