#!/bin/sh
#
# PiBoy DMG service
# Take care of alerting XPI that we should reboot or shutdown

start() {
	echo "Starting piboy-battery-indicator"
	start-stop-daemon -S -b /usr/bin/piboy-battery-indicator
	echo "OK"
}
stop() {
	printf "Stopping piboy: "
	sync
	# runlevel gives output like
	# 3 6
	# which means: last runlevel 3, wanted 6
	# 6 means reboot
	# 0 means shutdown
	if runlevel | grep -q '6$'; then
		# reboot requested
		echo "129" > /sys/kernel/xpi_gamecon/flags; sleep 1
	fi
	if runlevel | grep -q '0$'; then
		# shutdown requested
		echo "0" > /sys/kernel/xpi_gamecon/flags
		/sbin/rmmod xpi_gamecon
	fi
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?


