#!/bin/bash
#
# PiBoy DMG LCD service
# Take care of switching off LCD display if HDMI connected

theme="$(recalbox_settings  -command load -key emulationstation.theme.folder -default recalbox-goa2)"

start() {
  if grep -q -E '^connected' /sys/class/drm/card1-HDMI-A-*/status; then
    # disable LCD display
    echo 0 >/sys/kernel/xpi_gamecon/flags
    
    if [ "$theme" = "recalbox-goa2" ]; then
      recalbox_settings -command save -key emulationstation.theme.folder -value recalbox-next
    fi
  else
    # keep LCD enable change theme
    if [ "$theme" = "recalbox-next" ]; then
      recalbox_settings -command save -key emulationstation.theme.folder -value recalbox-goa2
    fi
  fi
}

case "$1" in
  start)
    start
  ;;
  *)
    echo "Usage: $0 start" 
    exit 1
esac

exit $?
