#!/bin/bash

# start only on boot and rpi4 arch
if [ "$1" != start ] || ! grep -q rpi4 /recalbox/recalbox.arch; then
  exit 1
fi

DESIRED_CEA_RESOLUTION=("1920x1080.*60Hz.*progressive" "1920x1080.*60Hz.*interlaced" \
                        "1280x720.*60Hz.*progressive" "1280x720.*60Hz.*interlaced")
DESIRED_DMT_RESOLUTION=("1920x1080.*60Hz.*progressive" "1920x1080.*60Hz.*interlaced" \
                        "1600x900.*60Hz.*progressive" "1600x900.*60Hz.*interlaced" \
                        "1280x1024.*60Hz.*progressive" "1280x1024.*60Hz.*interlaced" \
                        "1280x720.*60Hz.*progressive" "1280x720.*60Hz.*interlaced")

found_best_cea_resolution() {
  local MODE resolution
  for resolution in ${DESIRED_CEA_RESOLUTION[*]} ; do
    MODE=$(tvservice -m CEA |grep -E "$resolution" | sed 's/.*mode\s\([0-9]\+\).*/\1/')
    if [ -n "$MODE" ]; then
      echo "$MODE"
      return 0
    fi
  done
  return 1
}

found_best_dmt_resolution() {
  local MODE resolution
  for resolution in ${DESIRED_DMT_RESOLUTION[*]} ; do
    MODE=$(tvservice -m DMT |grep -E "$resolution" | sed 's/.*mode\s\([0-9]\+\).*/\1/')
    if [ -n "$MODE" ]; then
      echo "$MODE"
      return 0
    fi
  done
  return 1
}

if tvservice -s |head -n 1 |grep -q '3840x2160'; then
  EDID=$(tvservice -n | head -n 1 |cut -d = -f 2)
  echo "4k detected, force lower resolution for this monitor $EDID"

  GROUP=1
  MODE=$(found_best_cea_resolution)
  if [ -z "$MODE" ]; then
    GROUP=2
    MODE=$(found_best_dmt_resolution)
  fi

  if [ -z "$MODE" ]; then
    echo "no suitable mode found, using lowres mode" >&2
    GROUP=1
    MODE=1
  fi

  mount -o remount,rw /boot

  cat >>/boot/config.txt << EOF
# This configuration was added by $0
[EDID=$EDID]
hdmi_group=$GROUP
hdmi_mode=$MODE
[all]

EOF

  reboot
fi
