################################################################################
#
# kodi italian language resource
#
################################################################################

KODI_RESOURCE_LANGUAGE_IT_IT_RELEASE = matrix
KODI_RESOURCE_LANGUAGE_IT_IT_VERSION = 9.0.44
KODI_RESOURCE_LANGUAGE_IT_IT_PLUGINNAME = resource.language.it_it
KODI_RESOURCE_LANGUAGE_IT_IT_SOURCE = $(KODI_RESOURCE_LANGUAGE_IT_IT_PLUGINNAME)-$(KODI_RESOURCE_LANGUAGE_IT_IT_VERSION).zip
KODI_RESOURCE_LANGUAGE_IT_IT_SITE = https://mirrors.kodi.tv/addons/$(KODI_RESOURCE_LANGUAGE_IT_IT_RELEASE)/$(KODI_RESOURCE_LANGUAGE_IT_IT_PLUGINNAME)
KODI_RESOURCE_LANGUAGE_IT_IT_LICENSE = COPYRIGHT

KODI_RESOURCE_LANGUAGE_IT_IT_PLUGIN_TARGET_DIR=$(TARGET_DIR)/usr/share/kodi/addons

define KODI_RESOURCE_LANGUAGE_IT_IT_EXTRACT_CMDS
	@unzip -q -o $(DL_DIR)/kodi-resource-language-it_it/$(KODI_RESOURCE_LANGUAGE_IT_IT_SOURCE) -d $(@D)
endef

define KODI_RESOURCE_LANGUAGE_IT_IT_INSTALL_TARGET_CMDS
	@mkdir -p $(KODI_RESOURCE_LANGUAGE_IT_IT_PLUGIN_TARGET_DIR)
	@cp -r $(@D)/$(KODI_RESOURCE_LANGUAGE_IT_IT_PLUGINNAME) $(KODI_RESOURCE_LANGUAGE_IT_IT_PLUGIN_TARGET_DIR)
endef

$(eval $(generic-package))
