################################################################################
#
# THEPOWDERTOY
#
################################################################################

LIBRETRO_THEPOWDERTOY_VERSION = 1f58ea93445672e5f9219ff47b268e27e06d2387
LIBRETRO_THEPOWDERTOY_SITE = git://github.com/libretro/ThePowderToy.git
LIBRETRO_THEPOWDERTOY_LICENSE = GPLv3
LIBRETRO_THEPOWDERTOY_GIT_SUBMODULES=y

LIBRETRO_THEPOWDERTOY_CONF_OPTS=-DCMAKE_BUILD_TYPE=Release

define LIBRETRO_THEPOWDERTOY_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/src/thepowdertoy_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/thepowdertoy_libretro.so
endef

LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_SO)"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_SO)"
LIBRETRO_THEPOWDERTOY_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_SO)"

$(eval $(cmake-package))
