################################################################################
#
# rockchip-mali-bifrost-vulkan
#
################################################################################

ROCKCHIP_MALI_BIFROST_VULKAN_VERSION = r13p0
ROCKCHIP_MALI_BIFROST_VULKAN_SOURCE = rk3326_$(ROCKCHIP_MALI_BIFROST_VULKAN_VERSION)_gbm_with_vulkan_and_cl.zip
ROCKCHIP_MALI_BIFROST_VULKAN_SITE = https://dn.odroid.com/RK3326/ODROID-GO-Advance
ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_STAGING = YES

ROCKCHIP_MALI_BIFROST_VULKAN_LICENSE = COPYRIGHT

ROCKCHIP_MALI_BIFROST_VULKAN_LIB_FILE = libmali.so_rk3326_gbm_arm64_$(ROCKCHIP_MALI_BIFROST_VULKAN_VERSION)_with_vulkan_and_cl

define ROCKCHIP_MALI_BIFROST_VULKAN_EXTRACT_CMDS
	unzip $(ROCKCHIP_MALI_BIFROST_VULKAN_DL_DIR)/$(ROCKCHIP_MALI_BIFROST_VULKAN_SOURCE) -d $(@D)
endef

define ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_CMDS
	$(INSTALL) -D $(@D)/$(ROCKCHIP_MALI_BIFROST_VULKAN_LIB_FILE) $(1)/usr/lib/$(ROCKCHIP_MALI_LIB)
endef

define ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_TARGET_CMDS
	$(call ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_CMDS,$(TARGET_DIR))
endef

define ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_STAGING_CMDS
	$(call ROCKCHIP_MALI_BIFROST_VULKAN_INSTALL_CMDS,$(STAGING_DIR))
endef

$(eval $(generic-package))
