################################################################################
#
# solarus
#
################################################################################

SOLARUS_RECALBOX_SITE = https://gitlab.com/bkg2k/solarus.git
SOLARUS_RECALBOX_VERSION = c37611629f0ecd3db53dd152c97c09532ba2f754
SOLARUS_RECALBOX_SITE_METHOD = git

SOLARUS_RECALBOX_LICENSE = GPL-3.0 (code), CC-BY-SA-4.0 (Solarus logos and icons), \
	CC-BY-SA-3.0 (GUI icons)
SOLARUS_RECALBOX_LICENSE_FILES = license.txt license_gpl.txt

# Install libsolarus.so
#SOLARUS_RECALBOX_INSTALL_STAGING = YES

SOLARUS_RECALBOX_DEPENDENCIES = libmodplug libogg libvorbis openal physfs sdl2 \
	sdl2_image sdl2_ttf luajit glm

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
SOLARUS_RECALBOX_DEPENDENCIES += libgl
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
SOLARUS_RECALBOX_DEPENDENCIES += libgles
endif

define SOLARUS_RECALBOX_FIX_FINDOPENGLES
	cp $(SOLARUS_RECALBOX_PKGDIR)/FindOpenGLES2.cmake $(@D)/cmake/modules/
endef

SOLARUS_RECALBOX_PRE_CONFIGURE_HOOKS += SOLARUS_RECALBOX_FIX_FINDOPENGLES

# Disable launcher GUI (requires Qt5)
SOLARUS_RECALBOX_CONF_OPTS += -DSOLARUS_GUI=OFF
SOLARUS_RECALBOX_CONF_OPTS += -DSOLARUS_GL_ES=ON
SOLARUS_RECALBOX_CONF_OPTS += -DSOLARUS_BASE_WRITE_DIR="/recalbox/share/saves"
SOLARUS_RECALBOX_CONF_OPTS += -DSOLARUS_WRITE_DIR="solarus"
# -DSOLARUS_USE_LUAJIT=OFF

SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_SO)"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_SO)"
SOLARUS_RECALBOX_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_SO)"

$(eval $(cmake-package))
