################################################################################
#
# HATARI
#
################################################################################

LIBRETRO_HATARI_VERSION = 664ac30180064b7f616330d8ac16adf3dd78be12
LIBRETRO_HATARI_SITE = $(call github,libretro,hatari,$(LIBRETRO_HATARI_VERSION))
LIBRETRO_HATARI_LICENSE = GPL-2.0

LIBRETRO_HATARI_DEPENDENCIES = libcapsimage

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_X86_64)$(BR2_PACKAGE_RECALBOX_TARGET_X86),y)
LIBRETRO_HATARI_COMPILER_COMMONS_CFLAGS=$(COMPILER_COMMONS_CFLAGS_NOLTO)
LIBRETRO_HATARI_COMPILER_COMMONS_CXXFLAGS=$(COMPILER_COMMONS_CXXFLAGS_NOLTO)
LIBRETRO_HATARI_COMPILER_COMMONS_LDFLAGS=$(COMPILER_COMMONS_LDFLAGS_NOLTO)
else
LIBRETRO_HATARI_COMPILER_COMMONS_CFLAGS=$(COMPILER_COMMONS_CFLAGS_SO)
LIBRETRO_HATARI_COMPILER_COMMONS_CXXFLAGS=$(COMPILER_COMMONS_CXXFLAGS_SO)
LIBRETRO_HATARI_COMPILER_COMMONS_LDFLAGS=$(COMPILER_COMMONS_LDFLAGS_SO)
endif

define LIBRETRO_HATARI_BUILD_CMDS
	#$(SED) "s|-O2|-O3|g" $(@D)/Makefile.libretro
	CFLAGS="$(TARGET_CFLAGS) $(LIBRETRO_HATARI_COMPILER_COMMONS_CFLAGS)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) $(LIBRETRO_HATARI_COMPILER_COMMONS_CXXFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS) $(LIBRETRO_HATARI_COMPILER_COMMONS_LDFLAGS)" \
		ASFLAGS="$(TARGET_ASFLAGS)" PLATFLAGS="$(TARGET_PLATFLAGS)" SHARED="$(TARGET_SHARED)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile.libretro platform="$(RETROARCH_LIBRETRO_PLATFORM)"
endef

define LIBRETRO_HATARI_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/hatari_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/hatari_libretro.so
endef

$(eval $(generic-package))
