#!/bin/sh
#
# Starts volumed.
#

VOLUME_INPUT=$(grep -r -l 'gpio-keys' /sys/class/input/event*/device/name | sed 's#/sys/class#/dev#;s#/device.*##')

start() {
	printf "Starting volumed: "
	start-stop-daemon -S -x /usr/bin/volumed -- "$VOLUME_INPUT"
	echo "OK"
}
stop() {
	printf "Stopping volumed: "
	killall volumed
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

