--- a/shell/linux/Makefile
+++ b/shell/linux/Makefile
@@ -132,6 +132,16 @@
     endif
     undefine USE_X11
 
+# ROCKCHIP
+else ifneq (,$(findstring rockchip,$(platform)))
+    MFLAGS += -marm -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon -mfloat-abi=hard -funroll-loops
+    ASFLAGS += -march=armv8-a -mfpu=neon -mfloat-abi=hard
+    CFLAGS += -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant -DPNG_ARM_NEON=1 -DPNG_ARM_NEON_OPT=1
+    INCS += -I../linux-deps/include
+    LIBS += -lpng -lz
+    USE_GLES := 1
+    USE_SDL := 1
+
 # BeagleBone Black
 else ifneq (,$(findstring beagle,$(platform)))
     CC_PREFIX ?= arm-none-linux-gnueabi-
